//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.orders = new HashSet<order>();
        }
    
        public long client_id { get; set; }
        public string client_name { get; set; }
        public string client_surname { get; set; }
        public string client_jobtitle { get; set; }
        public string client_organisation { get; set; }
        public string client_email { get; set; }
        public string client_wphone { get; set; }
        public string client_fax { get; set; }
        public string client_skipe { get; set; }
        public string client_address { get; set; }
        public string client_description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}
