//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employees()
        {
            this.orders = new HashSet<orders>();
        }
    
        public long employee_id { get; set; }
        public string employee_login { get; set; }
        public string employee_password { get; set; }
        public string employee_name { get; set; }
        public string employee_surname { get; set; }
        public string employee_email { get; set; }
        public string employee_displayname { get; set; }
        public string employee_phone { get; set; }
        public string employee_mphone { get; set; }
        public string employee_wphone { get; set; }
        public string employee_fax { get; set; }
        public string employee_skype { get; set; }
        public string employee_hphone { get; set; }
        public string employee_address { get; set; }
        public string employee_description { get; set; }
        public long jobtitle_id { get; set; }
    
        public virtual job_titles job_titles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders { get; set; }
    }
}
