//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public supplier()
        {
            this.waybills = new HashSet<waybill>();
        }
    
        public long supplier_id { get; set; }
        public string supplier_name { get; set; }
        public string supplier_surname { get; set; }
        public string supplier_jobtitle { get; set; }
        public string supplier_organisation { get; set; }
        public string supplier_email { get; set; }
        public string supplier_mphone { get; set; }
        public string supplier_wphone { get; set; }
        public string supplier_fax { get; set; }
        public string supplier_skipe { get; set; }
        public string supplier_address { get; set; }
        public string supplier_description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<waybill> waybills { get; set; }
    }
}
