//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public supplies()
        {
            this.consumptions = new HashSet<consumptions>();
            this.rests = new HashSet<rests>();
        }
    
        public long supply_id { get; set; }
        public double supply_quantity { get; set; }
        public long material_id { get; set; }
        public double supply_summ { get; set; }
        public double supply_costunit { get; set; }
        public string supply_description { get; set; }
        public long waybill_id { get; set; }
        public System.DateTime supply_createtime { get; set; }
        public System.DateTime suppy_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consumptions> consumptions { get; set; }
        public virtual materials materials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rests> rests { get; set; }
        public virtual waybills waybills { get; set; }
    }
}
