/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using MySql.Data.MySqlClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity;

namespace ArtFlex
{
	public partial class frmconsumption : Form
	{
		private ModelArtFlexEntities ctx;
		
		public frmconsumption()
		{
			InitializeComponent();
		}
		
		private void frmconsumption_Load(object sender, EventArgs e)
		{
			ctx = new ModelArtFlexEntities();
			ctx.consumption.Load();
			BindingList<consumption> _entities = ctx.consumption.Local.ToBindingList();
			consumptionBindingSource.DataSource = _entities;
			this.consumption_idTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.consumptionBindingSource, "consumption_id", true ));
			this.supply_id_comboBox.DataSource = ctx.supply.ToList();
			this.supply_id_comboBox.DisplayMember = "supply_id";
			this.supply_id_comboBox.ValueMember = "supply_id";
			this.supply_id_comboBox.DataBindings.Add(new System.Windows.Forms.Binding("SelectedValue", this.consumptionBindingSource, "supply_id", true));

			this.material_id_comboBox.DataSource = ctx.materials.ToList();
			this.material_id_comboBox.DisplayMember = "material_id";
			this.material_id_comboBox.ValueMember = "material_id";
			this.material_id_comboBox.DataBindings.Add(new System.Windows.Forms.Binding("SelectedValue", this.consumptionBindingSource, "material_id", true));

			this.order_id_comboBox.DataSource = ctx.orders.ToList();
			this.order_id_comboBox.DisplayMember = "order_id";
			this.order_id_comboBox.ValueMember = "order_id";
			this.order_id_comboBox.DataBindings.Add(new System.Windows.Forms.Binding("SelectedValue", this.consumptionBindingSource, "order_id", true));

			this.consumption_quantityTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.consumptionBindingSource, "consumption_quantity", true ));
			this.consumption_date_dateTimePicker.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.consumptionBindingSource, "consumption_date", true ));
			this.consumption_createtimeTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.consumptionBindingSource, "consumption_createtime", true ));
			
		}
		
		private void Save_Click(object sender, EventArgs e)
		{
			if (!this.Validate()) return;
			consumptionBindingSource.EndEdit();
			ctx.SaveChanges();
			
		}
		
		private void frmconsumption_FormClosing(object sender, FormClosingEventArgs e)
		{
			e.Cancel = false;
		}
		
		private void consumption_idTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( consumption_idTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( consumption_idTextBox, "The field consumption_id is required" ); 
			}
			int v;
			string s = consumption_idTextBox.Text;
			if( !int.TryParse( s, out v ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( consumption_idTextBox, "The field consumption_id must be int." );
			}
			if( !e.Cancel ) { errorProvider1.SetError( consumption_idTextBox, "" ); } 
		}
		
		private void supply_id_comboBox_Validating(object sender, CancelEventArgs e)
		{
			int i = supply_id_comboBox.SelectedIndex;
			e.Cancel = false;
			if( i == -1 )
			{
				e.Cancel = true; 
				errorProvider1.SetError(supply_id_comboBox, "Must select a supply_id");
			}
			if( !e.Cancel )
			{
				errorProvider1.SetError(supply_id_comboBox, "");
			}
		}
		private void material_id_comboBox_Validating(object sender, CancelEventArgs e)
		{
			int i = material_id_comboBox.SelectedIndex;
			e.Cancel = false;
			if( i == -1 )
			{
				e.Cancel = true; 
				errorProvider1.SetError(material_id_comboBox, "Must select a material_id");
			}
			if( !e.Cancel )
			{
				errorProvider1.SetError(material_id_comboBox, "");
			}
		}
		private void order_id_comboBox_Validating(object sender, CancelEventArgs e)
		{
			int i = order_id_comboBox.SelectedIndex;
			e.Cancel = false;
			if( i == -1 )
			{
				e.Cancel = true; 
				errorProvider1.SetError(order_id_comboBox, "Must select a order_id");
			}
			if( !e.Cancel )
			{
				errorProvider1.SetError(order_id_comboBox, "");
			}
		}
		private void consumption_quantityTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( consumption_quantityTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( consumption_quantityTextBox, "The field consumption_quantity is required" ); 
			}
			double v;
			string s = consumption_quantityTextBox.Text;
			if( !double.TryParse( s, out v ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( consumption_quantityTextBox, "The field consumption_quantity must be double." );
			}
			if( !e.Cancel ) { errorProvider1.SetError( consumption_quantityTextBox, "" ); } 
		}
		
		
		
		
		private void bindingNavigatorAddNewItem_Click(object sender, EventArgs e)
		{
			consumptionBindingSource.AddNew();
		}
	}
}
