/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

namespace ArtFlex
{
	partial class frmclients
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}
		
		#region Windows Form Designer generated code
		
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmclients));
            this.bindingNavigator1 = new System.Windows.Forms.BindingNavigator(this.components);
            this.bindingNavigatorCountItem = new System.Windows.Forms.ToolStripLabel();
            this.bindingNavigatorDeleteItem = new System.Windows.Forms.ToolStripButton();
            this.bindingNavigatorMoveFirstItem = new System.Windows.Forms.ToolStripButton();
            this.bindingNavigatorMovePreviousItem = new System.Windows.Forms.ToolStripButton();
            this.bindingNavigatorSeparator = new System.Windows.Forms.ToolStripSeparator();
            this.bindingNavigatorPositionItem = new System.Windows.Forms.ToolStripTextBox();
            this.bindingNavigatorSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.bindingNavigatorMoveNextItem = new System.Windows.Forms.ToolStripButton();
            this.bindingNavigatorMoveLastItem = new System.Windows.Forms.ToolStripButton();
            this.bindingNavigatorSeparator2 = new System.Windows.Forms.ToolStripSeparator();
            this.bindingNavigatorAddNewItem = new System.Windows.Forms.ToolStripButton();
            this.toolStripButton1 = new System.Windows.Forms.ToolStripButton();
            this.clientsBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
            this.Panel1 = new System.Windows.Forms.Panel();
            this.client_idLabel = new System.Windows.Forms.Label();
            this.client_idTextBox = new System.Windows.Forms.TextBox();
            this.client_nameLabel = new System.Windows.Forms.Label();
            this.client_nameTextBox = new System.Windows.Forms.TextBox();
            this.client_surnameLabel = new System.Windows.Forms.Label();
            this.client_surnameTextBox = new System.Windows.Forms.TextBox();
            this.client_jobtitleLabel = new System.Windows.Forms.Label();
            this.client_jobtitleTextBox = new System.Windows.Forms.TextBox();
            this.client_organisationLabel = new System.Windows.Forms.Label();
            this.client_organisationTextBox = new System.Windows.Forms.TextBox();
            this.client_emailLabel = new System.Windows.Forms.Label();
            this.client_emailTextBox = new System.Windows.Forms.TextBox();
            this.client_wphoneLabel = new System.Windows.Forms.Label();
            this.client_wphoneTextBox = new System.Windows.Forms.TextBox();
            this.client_faxLabel = new System.Windows.Forms.Label();
            this.client_faxTextBox = new System.Windows.Forms.TextBox();
            this.client_skipeLabel = new System.Windows.Forms.Label();
            this.client_skipeTextBox = new System.Windows.Forms.TextBox();
            this.client_addressLabel = new System.Windows.Forms.Label();
            this.client_addressTextBox = new System.Windows.Forms.TextBox();
            this.client_descriptionLabel = new System.Windows.Forms.Label();
            this.client_descriptionTextBox = new System.Windows.Forms.TextBox();
            this.panel3 = new System.Windows.Forms.Panel();
            this.panel4 = new System.Windows.Forms.Panel();
            this.panel5 = new System.Windows.Forms.Panel();
            this.panel6 = new System.Windows.Forms.Panel();
            ((System.ComponentModel.ISupportInitialize)(this.bindingNavigator1)).BeginInit();
            this.bindingNavigator1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.clientsBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
            this.Panel1.SuspendLayout();
            this.panel3.SuspendLayout();
            this.SuspendLayout();
            // 
            // bindingNavigator1
            // 
            this.bindingNavigator1.AddNewItem = null;
            this.bindingNavigator1.BindingSource = this.clientsBindingSource;
            this.bindingNavigator1.CountItem = this.bindingNavigatorCountItem;
            this.bindingNavigator1.DeleteItem = this.bindingNavigatorDeleteItem;
            this.bindingNavigator1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.bindingNavigatorMoveFirstItem,
            this.bindingNavigatorMovePreviousItem,
            this.bindingNavigatorSeparator,
            this.bindingNavigatorPositionItem,
            this.bindingNavigatorCountItem,
            this.bindingNavigatorSeparator1,
            this.bindingNavigatorMoveNextItem,
            this.bindingNavigatorMoveLastItem,
            this.bindingNavigatorSeparator2,
            this.bindingNavigatorAddNewItem,
            this.bindingNavigatorDeleteItem,
            this.toolStripButton1});
            this.bindingNavigator1.Location = new System.Drawing.Point(0, 0);
            this.bindingNavigator1.MoveFirstItem = this.bindingNavigatorMoveFirstItem;
            this.bindingNavigator1.MoveLastItem = this.bindingNavigatorMoveLastItem;
            this.bindingNavigator1.MoveNextItem = this.bindingNavigatorMoveNextItem;
            this.bindingNavigator1.MovePreviousItem = this.bindingNavigatorMovePreviousItem;
            this.bindingNavigator1.Name = "bindingNavigator1";
            this.bindingNavigator1.Padding = new System.Windows.Forms.Padding(10, 0, 10, 0);
            this.bindingNavigator1.PositionItem = this.bindingNavigatorPositionItem;
            this.bindingNavigator1.Size = new System.Drawing.Size(778, 25);
            this.bindingNavigator1.TabIndex = 0;
            this.bindingNavigator1.Text = "bindingNavigator1";
            // 
            // bindingNavigatorCountItem
            // 
            this.bindingNavigatorCountItem.Name = "bindingNavigatorCountItem";
            this.bindingNavigatorCountItem.Size = new System.Drawing.Size(43, 22);
            this.bindingNavigatorCountItem.Text = "для {0}";
            this.bindingNavigatorCountItem.ToolTipText = "Total number of items";
            // 
            // bindingNavigatorDeleteItem
            // 
            this.bindingNavigatorDeleteItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorDeleteItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorDeleteItem.Image")));
            this.bindingNavigatorDeleteItem.Name = "bindingNavigatorDeleteItem";
            this.bindingNavigatorDeleteItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorDeleteItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorDeleteItem.Text = "Delete";
            // 
            // bindingNavigatorMoveFirstItem
            // 
            this.bindingNavigatorMoveFirstItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorMoveFirstItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveFirstItem.Image")));
            this.bindingNavigatorMoveFirstItem.Name = "bindingNavigatorMoveFirstItem";
            this.bindingNavigatorMoveFirstItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorMoveFirstItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorMoveFirstItem.Text = "Move first";
            // 
            // bindingNavigatorMovePreviousItem
            // 
            this.bindingNavigatorMovePreviousItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorMovePreviousItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMovePreviousItem.Image")));
            this.bindingNavigatorMovePreviousItem.Name = "bindingNavigatorMovePreviousItem";
            this.bindingNavigatorMovePreviousItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorMovePreviousItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorMovePreviousItem.Text = "Move previous";
            // 
            // bindingNavigatorSeparator
            // 
            this.bindingNavigatorSeparator.Name = "bindingNavigatorSeparator";
            this.bindingNavigatorSeparator.Size = new System.Drawing.Size(6, 25);
            // 
            // bindingNavigatorPositionItem
            // 
            this.bindingNavigatorPositionItem.AccessibleName = "Position";
            this.bindingNavigatorPositionItem.AutoSize = false;
            this.bindingNavigatorPositionItem.Name = "bindingNavigatorPositionItem";
            this.bindingNavigatorPositionItem.Size = new System.Drawing.Size(50, 23);
            this.bindingNavigatorPositionItem.Text = "0";
            this.bindingNavigatorPositionItem.ToolTipText = "Current position";
            // 
            // bindingNavigatorSeparator1
            // 
            this.bindingNavigatorSeparator1.Name = "bindingNavigatorSeparator1";
            this.bindingNavigatorSeparator1.Size = new System.Drawing.Size(6, 25);
            // 
            // bindingNavigatorMoveNextItem
            // 
            this.bindingNavigatorMoveNextItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorMoveNextItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveNextItem.Image")));
            this.bindingNavigatorMoveNextItem.Name = "bindingNavigatorMoveNextItem";
            this.bindingNavigatorMoveNextItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorMoveNextItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorMoveNextItem.Text = "Move next";
            // 
            // bindingNavigatorMoveLastItem
            // 
            this.bindingNavigatorMoveLastItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorMoveLastItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveLastItem.Image")));
            this.bindingNavigatorMoveLastItem.Name = "bindingNavigatorMoveLastItem";
            this.bindingNavigatorMoveLastItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorMoveLastItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorMoveLastItem.Text = "Move last";
            // 
            // bindingNavigatorSeparator2
            // 
            this.bindingNavigatorSeparator2.Name = "bindingNavigatorSeparator2";
            this.bindingNavigatorSeparator2.Size = new System.Drawing.Size(6, 25);
            // 
            // bindingNavigatorAddNewItem
            // 
            this.bindingNavigatorAddNewItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorAddNewItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorAddNewItem.Image")));
            this.bindingNavigatorAddNewItem.Name = "bindingNavigatorAddNewItem";
            this.bindingNavigatorAddNewItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorAddNewItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorAddNewItem.Text = "Add new";
            this.bindingNavigatorAddNewItem.Click += new System.EventHandler(this.bindingNavigatorAddNewItem_Click);
            // 
            // toolStripButton1
            // 
            this.toolStripButton1.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripButton1.Image = ((System.Drawing.Image)(resources.GetObject("toolStripButton1.Image")));
            this.toolStripButton1.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButton1.Name = "toolStripButton1";
            this.toolStripButton1.Size = new System.Drawing.Size(23, 22);
            this.toolStripButton1.Text = "Save";
            this.toolStripButton1.Click += new System.EventHandler(this.Save_Click);
            // 
            // errorProvider1
            // 
            this.errorProvider1.ContainerControl = this;
            // 
            // Panel1
            // 
            this.Panel1.AutoScroll = true;
            this.Panel1.AutoSize = true;
            this.Panel1.Controls.Add(this.client_idLabel);
            this.Panel1.Controls.Add(this.client_idTextBox);
            this.Panel1.Controls.Add(this.client_nameLabel);
            this.Panel1.Controls.Add(this.client_nameTextBox);
            this.Panel1.Controls.Add(this.client_surnameLabel);
            this.Panel1.Controls.Add(this.client_surnameTextBox);
            this.Panel1.Controls.Add(this.client_jobtitleLabel);
            this.Panel1.Controls.Add(this.client_jobtitleTextBox);
            this.Panel1.Controls.Add(this.client_organisationLabel);
            this.Panel1.Controls.Add(this.client_organisationTextBox);
            this.Panel1.Controls.Add(this.client_emailLabel);
            this.Panel1.Controls.Add(this.client_emailTextBox);
            this.Panel1.Controls.Add(this.client_wphoneLabel);
            this.Panel1.Controls.Add(this.client_wphoneTextBox);
            this.Panel1.Controls.Add(this.client_faxLabel);
            this.Panel1.Controls.Add(this.client_faxTextBox);
            this.Panel1.Controls.Add(this.client_skipeLabel);
            this.Panel1.Controls.Add(this.client_skipeTextBox);
            this.Panel1.Controls.Add(this.client_addressLabel);
            this.Panel1.Controls.Add(this.client_addressTextBox);
            this.Panel1.Controls.Add(this.client_descriptionLabel);
            this.Panel1.Controls.Add(this.client_descriptionTextBox);
            this.Panel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Panel1.Location = new System.Drawing.Point(10, 0);
            this.Panel1.Margin = new System.Windows.Forms.Padding(10, 3, 10, 3);
            this.Panel1.Name = "Panel1";
            this.Panel1.Size = new System.Drawing.Size(758, 350);
            this.Panel1.TabIndex = 1;
            // 
            // client_idLabel
            // 
            this.client_idLabel.AutoSize = true;
            this.client_idLabel.Location = new System.Drawing.Point(99, 50);
            this.client_idLabel.Name = "client_idLabel";
            this.client_idLabel.Size = new System.Drawing.Size(46, 13);
            this.client_idLabel.TabIndex = 1;
            this.client_idLabel.Text = "client_id";
            // 
            // client_idTextBox
            // 
            this.client_idTextBox.Location = new System.Drawing.Point(155, 50);
            this.client_idTextBox.Name = "client_idTextBox";
            this.client_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.client_idTextBox.TabIndex = 2;
            this.client_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.client_idTextBox_Validating);
            // 
            // client_nameLabel
            // 
            this.client_nameLabel.AutoSize = true;
            this.client_nameLabel.Location = new System.Drawing.Point(81, 76);
            this.client_nameLabel.Name = "client_nameLabel";
            this.client_nameLabel.Size = new System.Drawing.Size(64, 13);
            this.client_nameLabel.TabIndex = 3;
            this.client_nameLabel.Text = "client_name";
            // 
            // client_nameTextBox
            // 
            this.client_nameTextBox.Location = new System.Drawing.Point(155, 76);
            this.client_nameTextBox.Name = "client_nameTextBox";
            this.client_nameTextBox.Size = new System.Drawing.Size(100, 20);
            this.client_nameTextBox.TabIndex = 4;
            this.client_nameTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.client_nameTextBox_Validating);
            // 
            // client_surnameLabel
            // 
            this.client_surnameLabel.AutoSize = true;
            this.client_surnameLabel.Location = new System.Drawing.Point(67, 102);
            this.client_surnameLabel.Name = "client_surnameLabel";
            this.client_surnameLabel.Size = new System.Drawing.Size(78, 13);
            this.client_surnameLabel.TabIndex = 5;
            this.client_surnameLabel.Text = "client_surname";
            // 
            // client_surnameTextBox
            // 
            this.client_surnameTextBox.Location = new System.Drawing.Point(155, 102);
            this.client_surnameTextBox.Name = "client_surnameTextBox";
            this.client_surnameTextBox.Size = new System.Drawing.Size(100, 20);
            this.client_surnameTextBox.TabIndex = 6;
            this.client_surnameTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.client_surnameTextBox_Validating);
            // 
            // client_jobtitleLabel
            // 
            this.client_jobtitleLabel.AutoSize = true;
            this.client_jobtitleLabel.Location = new System.Drawing.Point(77, 128);
            this.client_jobtitleLabel.Name = "client_jobtitleLabel";
            this.client_jobtitleLabel.Size = new System.Drawing.Size(68, 13);
            this.client_jobtitleLabel.TabIndex = 7;
            this.client_jobtitleLabel.Text = "client_jobtitle";
            // 
            // client_jobtitleTextBox
            // 
            this.client_jobtitleTextBox.Location = new System.Drawing.Point(155, 128);
            this.client_jobtitleTextBox.Name = "client_jobtitleTextBox";
            this.client_jobtitleTextBox.Size = new System.Drawing.Size(100, 20);
            this.client_jobtitleTextBox.TabIndex = 8;
            this.client_jobtitleTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.client_jobtitleTextBox_Validating);
            // 
            // client_organisationLabel
            // 
            this.client_organisationLabel.AutoSize = true;
            this.client_organisationLabel.Location = new System.Drawing.Point(50, 154);
            this.client_organisationLabel.Name = "client_organisationLabel";
            this.client_organisationLabel.Size = new System.Drawing.Size(95, 13);
            this.client_organisationLabel.TabIndex = 9;
            this.client_organisationLabel.Text = "client_organisation";
            // 
            // client_organisationTextBox
            // 
            this.client_organisationTextBox.Location = new System.Drawing.Point(155, 154);
            this.client_organisationTextBox.Name = "client_organisationTextBox";
            this.client_organisationTextBox.Size = new System.Drawing.Size(100, 20);
            this.client_organisationTextBox.TabIndex = 10;
            this.client_organisationTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.client_organisationTextBox_Validating);
            // 
            // client_emailLabel
            // 
            this.client_emailLabel.AutoSize = true;
            this.client_emailLabel.Location = new System.Drawing.Point(398, 50);
            this.client_emailLabel.Name = "client_emailLabel";
            this.client_emailLabel.Size = new System.Drawing.Size(62, 13);
            this.client_emailLabel.TabIndex = 11;
            this.client_emailLabel.Text = "client_email";
            // 
            // client_emailTextBox
            // 
            this.client_emailTextBox.Location = new System.Drawing.Point(470, 50);
            this.client_emailTextBox.Name = "client_emailTextBox";
            this.client_emailTextBox.Size = new System.Drawing.Size(100, 20);
            this.client_emailTextBox.TabIndex = 12;
            this.client_emailTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.client_emailTextBox_Validating);
            // 
            // client_wphoneLabel
            // 
            this.client_wphoneLabel.AutoSize = true;
            this.client_wphoneLabel.Location = new System.Drawing.Point(384, 76);
            this.client_wphoneLabel.Name = "client_wphoneLabel";
            this.client_wphoneLabel.Size = new System.Drawing.Size(76, 13);
            this.client_wphoneLabel.TabIndex = 13;
            this.client_wphoneLabel.Text = "client_wphone";
            // 
            // client_wphoneTextBox
            // 
            this.client_wphoneTextBox.Location = new System.Drawing.Point(470, 76);
            this.client_wphoneTextBox.Name = "client_wphoneTextBox";
            this.client_wphoneTextBox.Size = new System.Drawing.Size(100, 20);
            this.client_wphoneTextBox.TabIndex = 14;
            this.client_wphoneTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.client_wphoneTextBox_Validating);
            // 
            // client_faxLabel
            // 
            this.client_faxLabel.AutoSize = true;
            this.client_faxLabel.Location = new System.Drawing.Point(408, 102);
            this.client_faxLabel.Name = "client_faxLabel";
            this.client_faxLabel.Size = new System.Drawing.Size(52, 13);
            this.client_faxLabel.TabIndex = 15;
            this.client_faxLabel.Text = "client_fax";
            // 
            // client_faxTextBox
            // 
            this.client_faxTextBox.Location = new System.Drawing.Point(470, 102);
            this.client_faxTextBox.Name = "client_faxTextBox";
            this.client_faxTextBox.Size = new System.Drawing.Size(100, 20);
            this.client_faxTextBox.TabIndex = 16;
            this.client_faxTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.client_faxTextBox_Validating);
            // 
            // client_skipeLabel
            // 
            this.client_skipeLabel.AutoSize = true;
            this.client_skipeLabel.Location = new System.Drawing.Point(397, 128);
            this.client_skipeLabel.Name = "client_skipeLabel";
            this.client_skipeLabel.Size = new System.Drawing.Size(63, 13);
            this.client_skipeLabel.TabIndex = 17;
            this.client_skipeLabel.Text = "client_skipe";
            // 
            // client_skipeTextBox
            // 
            this.client_skipeTextBox.Location = new System.Drawing.Point(470, 128);
            this.client_skipeTextBox.Name = "client_skipeTextBox";
            this.client_skipeTextBox.Size = new System.Drawing.Size(100, 20);
            this.client_skipeTextBox.TabIndex = 18;
            this.client_skipeTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.client_skipeTextBox_Validating);
            // 
            // client_addressLabel
            // 
            this.client_addressLabel.AutoSize = true;
            this.client_addressLabel.Location = new System.Drawing.Point(385, 154);
            this.client_addressLabel.Name = "client_addressLabel";
            this.client_addressLabel.Size = new System.Drawing.Size(75, 13);
            this.client_addressLabel.TabIndex = 19;
            this.client_addressLabel.Text = "client_address";
            // 
            // client_addressTextBox
            // 
            this.client_addressTextBox.Location = new System.Drawing.Point(470, 154);
            this.client_addressTextBox.Name = "client_addressTextBox";
            this.client_addressTextBox.Size = new System.Drawing.Size(100, 20);
            this.client_addressTextBox.TabIndex = 20;
            this.client_addressTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.client_addressTextBox_Validating);
            // 
            // client_descriptionLabel
            // 
            this.client_descriptionLabel.AutoSize = true;
            this.client_descriptionLabel.Location = new System.Drawing.Point(371, 180);
            this.client_descriptionLabel.Name = "client_descriptionLabel";
            this.client_descriptionLabel.Size = new System.Drawing.Size(89, 13);
            this.client_descriptionLabel.TabIndex = 21;
            this.client_descriptionLabel.Text = "client_description";
            // 
            // client_descriptionTextBox
            // 
            this.client_descriptionTextBox.Location = new System.Drawing.Point(470, 180);
            this.client_descriptionTextBox.Name = "client_descriptionTextBox";
            this.client_descriptionTextBox.Size = new System.Drawing.Size(100, 20);
            this.client_descriptionTextBox.TabIndex = 22;
            this.client_descriptionTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.client_descriptionTextBox_Validating);
            // 
            // panel3
            // 
            this.panel3.Controls.Add(this.Panel1);
            this.panel3.Controls.Add(this.panel4);
            this.panel3.Controls.Add(this.panel5);
            this.panel3.Controls.Add(this.panel6);
            this.panel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel3.Location = new System.Drawing.Point(0, 25);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(778, 360);
            this.panel3.TabIndex = 19;
            // 
            // panel4
            // 
            this.panel4.Dock = System.Windows.Forms.DockStyle.Right;
            this.panel4.Location = new System.Drawing.Point(768, 0);
            this.panel4.Name = "panel4";
            this.panel4.Size = new System.Drawing.Size(10, 350);
            this.panel4.TabIndex = 3;
            // 
            // panel5
            // 
            this.panel5.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel5.Location = new System.Drawing.Point(0, 0);
            this.panel5.Name = "panel5";
            this.panel5.Size = new System.Drawing.Size(10, 350);
            this.panel5.TabIndex = 5;
            // 
            // panel6
            // 
            this.panel6.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel6.Location = new System.Drawing.Point(0, 350);
            this.panel6.Name = "panel6";
            this.panel6.Size = new System.Drawing.Size(778, 10);
            this.panel6.TabIndex = 6;
            // 
            // frmclients
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoScroll = true;
            this.ClientSize = new System.Drawing.Size(778, 385);
            this.Controls.Add(this.panel3);
            this.Controls.Add(this.bindingNavigator1);
            this.Name = "frmclients";
            this.Text = "Clients";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmclients_FormClosing);
            this.Load += new System.EventHandler(this.frmclients_Load);
            ((System.ComponentModel.ISupportInitialize)(this.bindingNavigator1)).EndInit();
            this.bindingNavigator1.ResumeLayout(false);
            this.bindingNavigator1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.clientsBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
            this.Panel1.ResumeLayout(false);
            this.Panel1.PerformLayout();
            this.panel3.ResumeLayout(false);
            this.panel3.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

		}
		
		#endregion
		
		private System.Windows.Forms.BindingNavigator bindingNavigator1;
		private System.Windows.Forms.ToolStripButton bindingNavigatorAddNewItem;
		private System.Windows.Forms.ToolStripLabel bindingNavigatorCountItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorDeleteItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveFirstItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMovePreviousItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator;
		private System.Windows.Forms.ToolStripTextBox bindingNavigatorPositionItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator1;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveNextItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveLastItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator2;
		private System.Windows.Forms.ToolStripButton toolStripButton1;
		private System.Windows.Forms.ErrorProvider errorProvider1;
		private System.Windows.Forms.Panel Panel1;
		private System.Windows.Forms.BindingSource clientsBindingSource;
		private System.Windows.Forms.TextBox client_idTextBox;
		private System.Windows.Forms.Label client_idLabel;
		private System.Windows.Forms.TextBox client_nameTextBox;
		private System.Windows.Forms.Label client_nameLabel;
		private System.Windows.Forms.TextBox client_surnameTextBox;
		private System.Windows.Forms.Label client_surnameLabel;
		private System.Windows.Forms.TextBox client_jobtitleTextBox;
		private System.Windows.Forms.Label client_jobtitleLabel;
		private System.Windows.Forms.TextBox client_organisationTextBox;
		private System.Windows.Forms.Label client_organisationLabel;
		private System.Windows.Forms.TextBox client_emailTextBox;
		private System.Windows.Forms.Label client_emailLabel;
		private System.Windows.Forms.TextBox client_wphoneTextBox;
		private System.Windows.Forms.Label client_wphoneLabel;
		private System.Windows.Forms.TextBox client_faxTextBox;
		private System.Windows.Forms.Label client_faxLabel;
		private System.Windows.Forms.TextBox client_skipeTextBox;
		private System.Windows.Forms.Label client_skipeLabel;
		private System.Windows.Forms.TextBox client_addressTextBox;
		private System.Windows.Forms.Label client_addressLabel;
		private System.Windows.Forms.TextBox client_descriptionTextBox;
		private System.Windows.Forms.Label client_descriptionLabel;
		private System.Windows.Forms.Panel panel3;
		private System.Windows.Forms.Panel panel4;
		private System.Windows.Forms.Panel panel5;
		private System.Windows.Forms.Panel panel6;
		
	}
}

