/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

namespace ArtFlex
{
	partial class frmconsumption
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}
		
		#region Windows Form Designer generated code
		
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmconsumption));
            this.bindingNavigator1 = new System.Windows.Forms.BindingNavigator(this.components);
            this.bindingNavigatorCountItem = new System.Windows.Forms.ToolStripLabel();
            this.bindingNavigatorDeleteItem = new System.Windows.Forms.ToolStripButton();
            this.bindingNavigatorMoveFirstItem = new System.Windows.Forms.ToolStripButton();
            this.bindingNavigatorMovePreviousItem = new System.Windows.Forms.ToolStripButton();
            this.bindingNavigatorSeparator = new System.Windows.Forms.ToolStripSeparator();
            this.bindingNavigatorPositionItem = new System.Windows.Forms.ToolStripTextBox();
            this.bindingNavigatorSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.bindingNavigatorMoveNextItem = new System.Windows.Forms.ToolStripButton();
            this.bindingNavigatorMoveLastItem = new System.Windows.Forms.ToolStripButton();
            this.bindingNavigatorSeparator2 = new System.Windows.Forms.ToolStripSeparator();
            this.bindingNavigatorAddNewItem = new System.Windows.Forms.ToolStripButton();
            this.toolStripButton1 = new System.Windows.Forms.ToolStripButton();
            this.consumptionBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
            this.Panel1 = new System.Windows.Forms.Panel();
            this.consumption_idLabel = new System.Windows.Forms.Label();
            this.consumption_idTextBox = new System.Windows.Forms.TextBox();
            this.supply_idLabel = new System.Windows.Forms.Label();
            this.supply_id_comboBox = new System.Windows.Forms.ComboBox();
            this.material_idLabel = new System.Windows.Forms.Label();
            this.material_id_comboBox = new System.Windows.Forms.ComboBox();
            this.order_idLabel = new System.Windows.Forms.Label();
            this.order_id_comboBox = new System.Windows.Forms.ComboBox();
            this.consumption_quantityLabel = new System.Windows.Forms.Label();
            this.consumption_quantityTextBox = new System.Windows.Forms.TextBox();
            this.consumption_dateLabel = new System.Windows.Forms.Label();
            this.consumption_date_dateTimePicker = new System.Windows.Forms.DateTimePicker();
            this.consumption_createtimeLabel = new System.Windows.Forms.Label();
            this.consumption_createtimeTextBox = new System.Windows.Forms.TextBox();
            this.panel3 = new System.Windows.Forms.Panel();
            this.panel4 = new System.Windows.Forms.Panel();
            this.panel5 = new System.Windows.Forms.Panel();
            this.panel6 = new System.Windows.Forms.Panel();
            ((System.ComponentModel.ISupportInitialize)(this.bindingNavigator1)).BeginInit();
            this.bindingNavigator1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.consumptionBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
            this.Panel1.SuspendLayout();
            this.panel3.SuspendLayout();
            this.SuspendLayout();
            // 
            // bindingNavigator1
            // 
            this.bindingNavigator1.AddNewItem = null;
            this.bindingNavigator1.BindingSource = this.consumptionBindingSource;
            this.bindingNavigator1.CountItem = this.bindingNavigatorCountItem;
            this.bindingNavigator1.DeleteItem = this.bindingNavigatorDeleteItem;
            this.bindingNavigator1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.bindingNavigatorMoveFirstItem,
            this.bindingNavigatorMovePreviousItem,
            this.bindingNavigatorSeparator,
            this.bindingNavigatorPositionItem,
            this.bindingNavigatorCountItem,
            this.bindingNavigatorSeparator1,
            this.bindingNavigatorMoveNextItem,
            this.bindingNavigatorMoveLastItem,
            this.bindingNavigatorSeparator2,
            this.bindingNavigatorAddNewItem,
            this.bindingNavigatorDeleteItem,
            this.toolStripButton1});
            this.bindingNavigator1.Location = new System.Drawing.Point(0, 0);
            this.bindingNavigator1.MoveFirstItem = this.bindingNavigatorMoveFirstItem;
            this.bindingNavigator1.MoveLastItem = this.bindingNavigatorMoveLastItem;
            this.bindingNavigator1.MoveNextItem = this.bindingNavigatorMoveNextItem;
            this.bindingNavigator1.MovePreviousItem = this.bindingNavigatorMovePreviousItem;
            this.bindingNavigator1.Name = "bindingNavigator1";
            this.bindingNavigator1.Padding = new System.Windows.Forms.Padding(10, 0, 10, 0);
            this.bindingNavigator1.PositionItem = this.bindingNavigatorPositionItem;
            this.bindingNavigator1.Size = new System.Drawing.Size(795, 25);
            this.bindingNavigator1.TabIndex = 0;
            this.bindingNavigator1.Text = "bindingNavigator1";
            // 
            // bindingNavigatorCountItem
            // 
            this.bindingNavigatorCountItem.Name = "bindingNavigatorCountItem";
            this.bindingNavigatorCountItem.Size = new System.Drawing.Size(43, 22);
            this.bindingNavigatorCountItem.Text = "для {0}";
            this.bindingNavigatorCountItem.ToolTipText = "Total number of items";
            // 
            // bindingNavigatorDeleteItem
            // 
            this.bindingNavigatorDeleteItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorDeleteItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorDeleteItem.Image")));
            this.bindingNavigatorDeleteItem.Name = "bindingNavigatorDeleteItem";
            this.bindingNavigatorDeleteItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorDeleteItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorDeleteItem.Text = "Delete";
            // 
            // bindingNavigatorMoveFirstItem
            // 
            this.bindingNavigatorMoveFirstItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorMoveFirstItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveFirstItem.Image")));
            this.bindingNavigatorMoveFirstItem.Name = "bindingNavigatorMoveFirstItem";
            this.bindingNavigatorMoveFirstItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorMoveFirstItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorMoveFirstItem.Text = "Move first";
            // 
            // bindingNavigatorMovePreviousItem
            // 
            this.bindingNavigatorMovePreviousItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorMovePreviousItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMovePreviousItem.Image")));
            this.bindingNavigatorMovePreviousItem.Name = "bindingNavigatorMovePreviousItem";
            this.bindingNavigatorMovePreviousItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorMovePreviousItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorMovePreviousItem.Text = "Move previous";
            // 
            // bindingNavigatorSeparator
            // 
            this.bindingNavigatorSeparator.Name = "bindingNavigatorSeparator";
            this.bindingNavigatorSeparator.Size = new System.Drawing.Size(6, 25);
            // 
            // bindingNavigatorPositionItem
            // 
            this.bindingNavigatorPositionItem.AccessibleName = "Position";
            this.bindingNavigatorPositionItem.AutoSize = false;
            this.bindingNavigatorPositionItem.Name = "bindingNavigatorPositionItem";
            this.bindingNavigatorPositionItem.Size = new System.Drawing.Size(50, 23);
            this.bindingNavigatorPositionItem.Text = "0";
            this.bindingNavigatorPositionItem.ToolTipText = "Current position";
            // 
            // bindingNavigatorSeparator1
            // 
            this.bindingNavigatorSeparator1.Name = "bindingNavigatorSeparator1";
            this.bindingNavigatorSeparator1.Size = new System.Drawing.Size(6, 25);
            // 
            // bindingNavigatorMoveNextItem
            // 
            this.bindingNavigatorMoveNextItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorMoveNextItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveNextItem.Image")));
            this.bindingNavigatorMoveNextItem.Name = "bindingNavigatorMoveNextItem";
            this.bindingNavigatorMoveNextItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorMoveNextItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorMoveNextItem.Text = "Move next";
            // 
            // bindingNavigatorMoveLastItem
            // 
            this.bindingNavigatorMoveLastItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorMoveLastItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveLastItem.Image")));
            this.bindingNavigatorMoveLastItem.Name = "bindingNavigatorMoveLastItem";
            this.bindingNavigatorMoveLastItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorMoveLastItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorMoveLastItem.Text = "Move last";
            // 
            // bindingNavigatorSeparator2
            // 
            this.bindingNavigatorSeparator2.Name = "bindingNavigatorSeparator2";
            this.bindingNavigatorSeparator2.Size = new System.Drawing.Size(6, 25);
            // 
            // bindingNavigatorAddNewItem
            // 
            this.bindingNavigatorAddNewItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorAddNewItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorAddNewItem.Image")));
            this.bindingNavigatorAddNewItem.Name = "bindingNavigatorAddNewItem";
            this.bindingNavigatorAddNewItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorAddNewItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorAddNewItem.Text = "Add new";
            this.bindingNavigatorAddNewItem.Click += new System.EventHandler(this.bindingNavigatorAddNewItem_Click);
            // 
            // toolStripButton1
            // 
            this.toolStripButton1.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripButton1.Image = ((System.Drawing.Image)(resources.GetObject("toolStripButton1.Image")));
            this.toolStripButton1.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButton1.Name = "toolStripButton1";
            this.toolStripButton1.Size = new System.Drawing.Size(23, 22);
            this.toolStripButton1.Text = "Save";
            this.toolStripButton1.Click += new System.EventHandler(this.Save_Click);
            // 
            // errorProvider1
            // 
            this.errorProvider1.ContainerControl = this;
            // 
            // Panel1
            // 
            this.Panel1.AutoScroll = true;
            this.Panel1.AutoSize = true;
            this.Panel1.Controls.Add(this.consumption_idLabel);
            this.Panel1.Controls.Add(this.consumption_idTextBox);
            this.Panel1.Controls.Add(this.supply_idLabel);
            this.Panel1.Controls.Add(this.supply_id_comboBox);
            this.Panel1.Controls.Add(this.material_idLabel);
            this.Panel1.Controls.Add(this.material_id_comboBox);
            this.Panel1.Controls.Add(this.order_idLabel);
            this.Panel1.Controls.Add(this.order_id_comboBox);
            this.Panel1.Controls.Add(this.consumption_quantityLabel);
            this.Panel1.Controls.Add(this.consumption_quantityTextBox);
            this.Panel1.Controls.Add(this.consumption_dateLabel);
            this.Panel1.Controls.Add(this.consumption_date_dateTimePicker);
            this.Panel1.Controls.Add(this.consumption_createtimeLabel);
            this.Panel1.Controls.Add(this.consumption_createtimeTextBox);
            this.Panel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Panel1.Location = new System.Drawing.Point(10, 0);
            this.Panel1.Margin = new System.Windows.Forms.Padding(10, 3, 10, 3);
            this.Panel1.Name = "Panel1";
            this.Panel1.Size = new System.Drawing.Size(775, 325);
            this.Panel1.TabIndex = 1;
            // 
            // consumption_idLabel
            // 
            this.consumption_idLabel.AutoSize = true;
            this.consumption_idLabel.Location = new System.Drawing.Point(91, 50);
            this.consumption_idLabel.Name = "consumption_idLabel";
            this.consumption_idLabel.Size = new System.Drawing.Size(81, 13);
            this.consumption_idLabel.TabIndex = 1;
            this.consumption_idLabel.Text = "consumption_id";
            // 
            // consumption_idTextBox
            // 
            this.consumption_idTextBox.Location = new System.Drawing.Point(182, 50);
            this.consumption_idTextBox.Name = "consumption_idTextBox";
            this.consumption_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.consumption_idTextBox.TabIndex = 2;
            this.consumption_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.consumption_idTextBox_Validating);
            // 
            // supply_idLabel
            // 
            this.supply_idLabel.AutoSize = true;
            this.supply_idLabel.Location = new System.Drawing.Point(121, 76);
            this.supply_idLabel.Name = "supply_idLabel";
            this.supply_idLabel.Size = new System.Drawing.Size(51, 13);
            this.supply_idLabel.TabIndex = 3;
            this.supply_idLabel.Text = "supply_id";
            // 
            // supply_id_comboBox
            // 
            this.supply_id_comboBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Append;
            this.supply_id_comboBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
            this.supply_id_comboBox.FormattingEnabled = true;
            this.supply_id_comboBox.Location = new System.Drawing.Point(182, 76);
            this.supply_id_comboBox.Name = "supply_id_comboBox";
            this.supply_id_comboBox.Size = new System.Drawing.Size(206, 21);
            this.supply_id_comboBox.TabIndex = 4;
            this.supply_id_comboBox.Validating += new System.ComponentModel.CancelEventHandler(this.supply_id_comboBox_Validating);
            // 
            // material_idLabel
            // 
            this.material_idLabel.AutoSize = true;
            this.material_idLabel.Location = new System.Drawing.Point(115, 102);
            this.material_idLabel.Name = "material_idLabel";
            this.material_idLabel.Size = new System.Drawing.Size(57, 13);
            this.material_idLabel.TabIndex = 5;
            this.material_idLabel.Text = "material_id";
            // 
            // material_id_comboBox
            // 
            this.material_id_comboBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Append;
            this.material_id_comboBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
            this.material_id_comboBox.FormattingEnabled = true;
            this.material_id_comboBox.Location = new System.Drawing.Point(182, 102);
            this.material_id_comboBox.Name = "material_id_comboBox";
            this.material_id_comboBox.Size = new System.Drawing.Size(206, 21);
            this.material_id_comboBox.TabIndex = 6;
            this.material_id_comboBox.Validating += new System.ComponentModel.CancelEventHandler(this.material_id_comboBox_Validating);
            // 
            // order_idLabel
            // 
            this.order_idLabel.AutoSize = true;
            this.order_idLabel.Location = new System.Drawing.Point(469, 50);
            this.order_idLabel.Name = "order_idLabel";
            this.order_idLabel.Size = new System.Drawing.Size(45, 13);
            this.order_idLabel.TabIndex = 7;
            this.order_idLabel.Text = "order_id";
            // 
            // order_id_comboBox
            // 
            this.order_id_comboBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Append;
            this.order_id_comboBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
            this.order_id_comboBox.FormattingEnabled = true;
            this.order_id_comboBox.Location = new System.Drawing.Point(524, 50);
            this.order_id_comboBox.Name = "order_id_comboBox";
            this.order_id_comboBox.Size = new System.Drawing.Size(206, 21);
            this.order_id_comboBox.TabIndex = 8;
            this.order_id_comboBox.Validating += new System.ComponentModel.CancelEventHandler(this.order_id_comboBox_Validating);
            // 
            // consumption_quantityLabel
            // 
            this.consumption_quantityLabel.AutoSize = true;
            this.consumption_quantityLabel.Location = new System.Drawing.Point(404, 76);
            this.consumption_quantityLabel.Name = "consumption_quantityLabel";
            this.consumption_quantityLabel.Size = new System.Drawing.Size(110, 13);
            this.consumption_quantityLabel.TabIndex = 9;
            this.consumption_quantityLabel.Text = "consumption_quantity";
            // 
            // consumption_quantityTextBox
            // 
            this.consumption_quantityTextBox.Location = new System.Drawing.Point(524, 76);
            this.consumption_quantityTextBox.Name = "consumption_quantityTextBox";
            this.consumption_quantityTextBox.Size = new System.Drawing.Size(100, 20);
            this.consumption_quantityTextBox.TabIndex = 10;
            this.consumption_quantityTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.consumption_quantityTextBox_Validating);
            // 
            // consumption_dateLabel
            // 
            this.consumption_dateLabel.AutoSize = true;
            this.consumption_dateLabel.Location = new System.Drawing.Point(420, 102);
            this.consumption_dateLabel.Name = "consumption_dateLabel";
            this.consumption_dateLabel.Size = new System.Drawing.Size(94, 13);
            this.consumption_dateLabel.TabIndex = 11;
            this.consumption_dateLabel.Text = "consumption_date";
            // 
            // consumption_date_dateTimePicker
            // 
            this.consumption_date_dateTimePicker.CustomFormat = "dd/MM/yyyy";
            this.consumption_date_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.consumption_date_dateTimePicker.Location = new System.Drawing.Point(524, 102);
            this.consumption_date_dateTimePicker.Name = "consumption_date_dateTimePicker";
            this.consumption_date_dateTimePicker.Size = new System.Drawing.Size(200, 20);
            this.consumption_date_dateTimePicker.TabIndex = 12;
            this.consumption_date_dateTimePicker.Value = new System.DateTime(2014, 5, 26, 17, 35, 11, 0);
            // 
            // consumption_createtimeLabel
            // 
            this.consumption_createtimeLabel.AutoSize = true;
            this.consumption_createtimeLabel.Location = new System.Drawing.Point(392, 128);
            this.consumption_createtimeLabel.Name = "consumption_createtimeLabel";
            this.consumption_createtimeLabel.Size = new System.Drawing.Size(122, 13);
            this.consumption_createtimeLabel.TabIndex = 13;
            this.consumption_createtimeLabel.Text = "consumption_createtime";
            // 
            // consumption_createtimeTextBox
            // 
            this.consumption_createtimeTextBox.Enabled = false;
            this.consumption_createtimeTextBox.Location = new System.Drawing.Point(524, 128);
            this.consumption_createtimeTextBox.Name = "consumption_createtimeTextBox";
            this.consumption_createtimeTextBox.Size = new System.Drawing.Size(100, 20);
            this.consumption_createtimeTextBox.TabIndex = 14;
            // 
            // panel3
            // 
            this.panel3.Controls.Add(this.Panel1);
            this.panel3.Controls.Add(this.panel4);
            this.panel3.Controls.Add(this.panel5);
            this.panel3.Controls.Add(this.panel6);
            this.panel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel3.Location = new System.Drawing.Point(0, 25);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(795, 335);
            this.panel3.TabIndex = 19;
            // 
            // panel4
            // 
            this.panel4.Dock = System.Windows.Forms.DockStyle.Right;
            this.panel4.Location = new System.Drawing.Point(785, 0);
            this.panel4.Name = "panel4";
            this.panel4.Size = new System.Drawing.Size(10, 325);
            this.panel4.TabIndex = 3;
            // 
            // panel5
            // 
            this.panel5.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel5.Location = new System.Drawing.Point(0, 0);
            this.panel5.Name = "panel5";
            this.panel5.Size = new System.Drawing.Size(10, 325);
            this.panel5.TabIndex = 5;
            // 
            // panel6
            // 
            this.panel6.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel6.Location = new System.Drawing.Point(0, 325);
            this.panel6.Name = "panel6";
            this.panel6.Size = new System.Drawing.Size(795, 10);
            this.panel6.TabIndex = 6;
            // 
            // frmconsumption
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoScroll = true;
            this.ClientSize = new System.Drawing.Size(795, 360);
            this.Controls.Add(this.panel3);
            this.Controls.Add(this.bindingNavigator1);
            this.Name = "frmconsumption";
            this.Text = "Consumption";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmconsumption_FormClosing);
            this.Load += new System.EventHandler(this.frmconsumption_Load);
            ((System.ComponentModel.ISupportInitialize)(this.bindingNavigator1)).EndInit();
            this.bindingNavigator1.ResumeLayout(false);
            this.bindingNavigator1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.consumptionBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
            this.Panel1.ResumeLayout(false);
            this.Panel1.PerformLayout();
            this.panel3.ResumeLayout(false);
            this.panel3.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

		}
		
		#endregion
		
		private System.Windows.Forms.BindingNavigator bindingNavigator1;
		private System.Windows.Forms.ToolStripButton bindingNavigatorAddNewItem;
		private System.Windows.Forms.ToolStripLabel bindingNavigatorCountItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorDeleteItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveFirstItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMovePreviousItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator;
		private System.Windows.Forms.ToolStripTextBox bindingNavigatorPositionItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator1;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveNextItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveLastItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator2;
		private System.Windows.Forms.ToolStripButton toolStripButton1;
		private System.Windows.Forms.ErrorProvider errorProvider1;
		private System.Windows.Forms.Panel Panel1;
		private System.Windows.Forms.BindingSource consumptionBindingSource;
		private System.Windows.Forms.TextBox consumption_idTextBox;
		private System.Windows.Forms.Label consumption_idLabel;
		private System.Windows.Forms.ComboBox supply_id_comboBox;
		private System.Windows.Forms.Label supply_idLabel;
		private System.Windows.Forms.ComboBox material_id_comboBox;
		private System.Windows.Forms.Label material_idLabel;
		private System.Windows.Forms.ComboBox order_id_comboBox;
		private System.Windows.Forms.Label order_idLabel;
		private System.Windows.Forms.TextBox consumption_quantityTextBox;
		private System.Windows.Forms.Label consumption_quantityLabel;
		private System.Windows.Forms.DateTimePicker consumption_date_dateTimePicker;
		private System.Windows.Forms.Label consumption_dateLabel;
		private System.Windows.Forms.TextBox consumption_createtimeTextBox;
		private System.Windows.Forms.Label consumption_createtimeLabel;
		private System.Windows.Forms.Panel panel3;
		private System.Windows.Forms.Panel panel4;
		private System.Windows.Forms.Panel panel5;
		private System.Windows.Forms.Panel panel6;
		
	}
}

