/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using MySql.Data.MySqlClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity;
using MySqlDB;

namespace ArtFlex
{
	public partial class frmcategories : Form
	{
		private ModelEntities context;
		
		public frmcategories()
		{
			InitializeComponent();
		}
		
		private void frmcategories_Load(object sender, EventArgs e)
		{
			context = new ModelEntities();
			context.categories.Load();
			BindingList<categories> _entities = context.categories.Local.ToBindingList();
			categoriesBindingSource.DataSource = _entities;
			this.category_idTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.categoriesBindingSource, "category_id", true ));
			this.category_nameTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.categoriesBindingSource, "category_name", true ));
			
		}
		
		private void Save_Click(object sender, EventArgs e)
		{
			if (!this.Validate()) return;
			categoriesBindingSource.EndEdit();
			context.SaveChanges();
			
		}
		
		private void frmcategories_FormClosing(object sender, FormClosingEventArgs e)
		{
			e.Cancel = false;
		}
		
		private void category_idTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( category_idTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( category_idTextBox, "The field category_id is required" ); 
			}
			int v;
			string s = category_idTextBox.Text;
			if( !int.TryParse( s, out v ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( category_idTextBox, "The field category_id must be int." );
			}
			if( !e.Cancel ) { errorProvider1.SetError( category_idTextBox, "" ); } 
		}
		
		private void category_nameTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( category_nameTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( category_nameTextBox, "The field category_name is required" ); 
			}
			if( !e.Cancel ) { errorProvider1.SetError( category_nameTextBox, "" ); } 
		}
		
		
		
		
		private void bindingNavigatorAddNewItem_Click(object sender, EventArgs e)
		{
			categoriesBindingSource.AddNew();
		}
	}
}
