/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

namespace ArtFlex
{
	partial class frmemployees
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}
		
		#region Windows Form Designer generated code
		
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.components = new System.ComponentModel.Container();
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmemployees));
			this.bindingNavigator1 = new System.Windows.Forms.BindingNavigator(this.components);
			this.bindingNavigatorAddNewItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorCountItem = new System.Windows.Forms.ToolStripLabel();
			this.bindingNavigatorDeleteItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorMoveFirstItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorMovePreviousItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorSeparator = new System.Windows.Forms.ToolStripSeparator();
			this.bindingNavigatorPositionItem = new System.Windows.Forms.ToolStripTextBox();
			this.bindingNavigatorSeparator1 = new System.Windows.Forms.ToolStripSeparator();
			this.bindingNavigatorMoveNextItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorMoveLastItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorSeparator2 = new System.Windows.Forms.ToolStripSeparator();
			this.toolStripButton1 = new System.Windows.Forms.ToolStripButton();
			this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
			
			this.Panel1 = new System.Windows.Forms.Panel();
			
			this.employeesBindingSource = new System.Windows.Forms.BindingSource(this.components);
			this.panel3 = new System.Windows.Forms.Panel();
			this.panel4 = new System.Windows.Forms.Panel();
			this.panel5 = new System.Windows.Forms.Panel();
			this.panel6 = new System.Windows.Forms.Panel();
			
			((System.ComponentModel.ISupportInitialize)(this.bindingNavigator1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
			this.bindingNavigator1.SuspendLayout();
			this.panel3.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.employeesBindingSource)).BeginInit();
			
			this.Panel1.SuspendLayout();
			this.SuspendLayout();
			// 
			// bindingNavigator1
			// 
			this.bindingNavigator1.AddNewItem = null;
			this.bindingNavigator1.CountItem = this.bindingNavigatorCountItem;
			this.bindingNavigator1.DeleteItem = this.bindingNavigatorDeleteItem;
			this.bindingNavigator1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
			this.bindingNavigatorMoveFirstItem,
			this.bindingNavigatorMovePreviousItem,
			this.bindingNavigatorSeparator,
			this.bindingNavigatorPositionItem,
			this.bindingNavigatorCountItem,
			this.bindingNavigatorSeparator1,
			this.bindingNavigatorMoveNextItem,
			this.bindingNavigatorMoveLastItem,
			this.bindingNavigatorSeparator2,
			this.bindingNavigatorAddNewItem,
			this.bindingNavigatorDeleteItem,
			this.toolStripButton1});
			this.bindingNavigator1.Location = new System.Drawing.Point(0, 0);
			this.bindingNavigator1.MoveFirstItem = this.bindingNavigatorMoveFirstItem;
			this.bindingNavigator1.MoveLastItem = this.bindingNavigatorMoveLastItem;
			this.bindingNavigator1.MoveNextItem = this.bindingNavigatorMoveNextItem;
			this.bindingNavigator1.MovePreviousItem = this.bindingNavigatorMovePreviousItem;
			this.bindingNavigator1.Name = "bindingNavigator1";
			this.bindingNavigator1.Padding = new System.Windows.Forms.Padding(10, 0, 10, 0);
			this.bindingNavigator1.PositionItem = this.bindingNavigatorPositionItem;
			this.bindingNavigator1.Size = new System.Drawing.Size(360, 25);
			this.bindingNavigator1.TabIndex = 0;
			this.bindingNavigator1.Text = "bindingNavigator1";
			// 
			// bindingNavigatorAddNewItem
			// 
			this.bindingNavigatorAddNewItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorAddNewItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorAddNewItem.Image")));
			this.bindingNavigatorAddNewItem.Name = "bindingNavigatorAddNewItem";
			this.bindingNavigatorAddNewItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorAddNewItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorAddNewItem.Text = "Add new";
			this.bindingNavigatorAddNewItem.Click += new System.EventHandler(this.bindingNavigatorAddNewItem_Click);
			// 
			// bindingNavigatorCountItem
			// 
			this.bindingNavigatorCountItem.Name = "bindingNavigatorCountItem";
			this.bindingNavigatorCountItem.Size = new System.Drawing.Size(35, 22);
			this.bindingNavigatorCountItem.Text = "of {0}";
			this.bindingNavigatorCountItem.ToolTipText = "Total number of items";
			// 
			// bindingNavigatorDeleteItem
			// 
			this.bindingNavigatorDeleteItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorDeleteItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorDeleteItem.Image")));
			this.bindingNavigatorDeleteItem.Name = "bindingNavigatorDeleteItem";
			this.bindingNavigatorDeleteItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorDeleteItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorDeleteItem.Text = "Delete";
			// 
			// bindingNavigatorMoveFirstItem
			// 
			this.bindingNavigatorMoveFirstItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorMoveFirstItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveFirstItem.Image")));
			this.bindingNavigatorMoveFirstItem.Name = "bindingNavigatorMoveFirstItem";
			this.bindingNavigatorMoveFirstItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorMoveFirstItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorMoveFirstItem.Text = "Move first";
			// 
			// bindingNavigatorMovePreviousItem
			// 
			this.bindingNavigatorMovePreviousItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorMovePreviousItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMovePreviousItem.Image")));
			this.bindingNavigatorMovePreviousItem.Name = "bindingNavigatorMovePreviousItem";
			this.bindingNavigatorMovePreviousItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorMovePreviousItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorMovePreviousItem.Text = "Move previous";
			// 
			// bindingNavigatorSeparator
			// 
			this.bindingNavigatorSeparator.Name = "bindingNavigatorSeparator";
			this.bindingNavigatorSeparator.Size = new System.Drawing.Size(6, 25);
			// 
			// bindingNavigatorPositionItem
			// 
			this.bindingNavigatorPositionItem.AccessibleName = "Position";
			this.bindingNavigatorPositionItem.AutoSize = false;
			this.bindingNavigatorPositionItem.Name = "bindingNavigatorPositionItem";
			this.bindingNavigatorPositionItem.Size = new System.Drawing.Size(50, 23);
			this.bindingNavigatorPositionItem.Text = "0";
			this.bindingNavigatorPositionItem.ToolTipText = "Current position";
			// 
			// bindingNavigatorSeparator1
			// 
			this.bindingNavigatorSeparator1.Name = "bindingNavigatorSeparator1";
			this.bindingNavigatorSeparator1.Size = new System.Drawing.Size(6, 25);
			// 
			// bindingNavigatorMoveNextItem
			// 
			this.bindingNavigatorMoveNextItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorMoveNextItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveNextItem.Image")));
			this.bindingNavigatorMoveNextItem.Name = "bindingNavigatorMoveNextItem";
			this.bindingNavigatorMoveNextItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorMoveNextItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorMoveNextItem.Text = "Move next";
			// 
			// bindingNavigatorMoveLastItem
			// 
			this.bindingNavigatorMoveLastItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorMoveLastItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveLastItem.Image")));
			this.bindingNavigatorMoveLastItem.Name = "bindingNavigatorMoveLastItem";
			this.bindingNavigatorMoveLastItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorMoveLastItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorMoveLastItem.Text = "Move last";
			// 
			// bindingNavigatorSeparator2
			// 
			this.bindingNavigatorSeparator2.Name = "bindingNavigatorSeparator2";
			this.bindingNavigatorSeparator2.Size = new System.Drawing.Size(6, 25);
			// 
			// toolStripButton1
			// 
			this.toolStripButton1.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.toolStripButton1.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorSaveItem.Image")));
			this.toolStripButton1.ImageTransparentColor = System.Drawing.Color.Magenta;
			this.toolStripButton1.Name = "toolStripButton1";
			this.toolStripButton1.Size = new System.Drawing.Size(23, 22);
			this.toolStripButton1.Text = "Save";
			this.toolStripButton1.Click += new System.EventHandler(this.Save_Click);
			// 
			// errorProvider1
			// 
			this.errorProvider1.ContainerControl = this;
			//
			// Panel1
			//
			this.Panel1.AutoScroll = true;
			this.Panel1.Dock = System.Windows.Forms.DockStyle.Fill;
			this.Panel1.Location = new System.Drawing.Point(0, 25);
			this.Panel1.Margin = new System.Windows.Forms.Padding(10, 3, 10, 3);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new System.Drawing.Size(656, 183);
			this.Panel1.TabIndex = 1;
			this.Panel1.AutoSize = true;
			
			this.bindingNavigator1.BindingSource = this.employeesBindingSource;
			//
			// employee_idLabel
			//
			this.employee_idLabel = new System.Windows.Forms.Label();
			this.employee_idLabel.AutoSize = true;
			this.employee_idLabel.Location = new System.Drawing.Point( 100, 50 );
			this.employee_idLabel.Name = "employee_idLabel";
			this.employee_idLabel.Size = new System.Drawing.Size( 66, 13 );
			this.employee_idLabel.TabIndex = 1;
			this.employee_idLabel.Text = "employee_id";
			this.Panel1.Controls.Add( this.employee_idLabel );
			//
			// employee_idTextBox
			//
			this.employee_idTextBox = new System.Windows.Forms.TextBox();
			this.employee_idTextBox.Location = new System.Drawing.Point( 176, 50 );
			this.employee_idTextBox.Name = "employee_idTextBox";
			this.employee_idTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.employee_idTextBox.TabIndex = 2;
			this.employee_idTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.employee_idTextBox_Validating );
			this.Panel1.Controls.Add( this.employee_idTextBox);
			//
			// employee_loginLabel
			//
			this.employee_loginLabel = new System.Windows.Forms.Label();
			this.employee_loginLabel.AutoSize = true;
			this.employee_loginLabel.Location = new System.Drawing.Point( 86, 76 );
			this.employee_loginLabel.Name = "employee_loginLabel";
			this.employee_loginLabel.Size = new System.Drawing.Size( 80, 13 );
			this.employee_loginLabel.TabIndex = 3;
			this.employee_loginLabel.Text = "employee_login";
			this.Panel1.Controls.Add( this.employee_loginLabel );
			//
			// employee_loginTextBox
			//
			this.employee_loginTextBox = new System.Windows.Forms.TextBox();
			this.employee_loginTextBox.Location = new System.Drawing.Point( 176, 76 );
			this.employee_loginTextBox.Name = "employee_loginTextBox";
			this.employee_loginTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.employee_loginTextBox.TabIndex = 4;
			this.employee_loginTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.employee_loginTextBox_Validating );
			this.Panel1.Controls.Add( this.employee_loginTextBox);
			//
			// employee_passwordLabel
			//
			this.employee_passwordLabel = new System.Windows.Forms.Label();
			this.employee_passwordLabel.AutoSize = true;
			this.employee_passwordLabel.Location = new System.Drawing.Point( 63, 102 );
			this.employee_passwordLabel.Name = "employee_passwordLabel";
			this.employee_passwordLabel.Size = new System.Drawing.Size( 103, 13 );
			this.employee_passwordLabel.TabIndex = 5;
			this.employee_passwordLabel.Text = "employee_password";
			this.Panel1.Controls.Add( this.employee_passwordLabel );
			//
			// employee_passwordTextBox
			//
			this.employee_passwordTextBox = new System.Windows.Forms.TextBox();
			this.employee_passwordTextBox.Location = new System.Drawing.Point( 176, 102 );
			this.employee_passwordTextBox.Name = "employee_passwordTextBox";
			this.employee_passwordTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.employee_passwordTextBox.TabIndex = 6;
			this.employee_passwordTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.employee_passwordTextBox_Validating );
			this.Panel1.Controls.Add( this.employee_passwordTextBox);
			//
			// employee_nameLabel
			//
			this.employee_nameLabel = new System.Windows.Forms.Label();
			this.employee_nameLabel.AutoSize = true;
			this.employee_nameLabel.Location = new System.Drawing.Point( 82, 128 );
			this.employee_nameLabel.Name = "employee_nameLabel";
			this.employee_nameLabel.Size = new System.Drawing.Size( 84, 13 );
			this.employee_nameLabel.TabIndex = 7;
			this.employee_nameLabel.Text = "employee_name";
			this.Panel1.Controls.Add( this.employee_nameLabel );
			//
			// employee_nameTextBox
			//
			this.employee_nameTextBox = new System.Windows.Forms.TextBox();
			this.employee_nameTextBox.Location = new System.Drawing.Point( 176, 128 );
			this.employee_nameTextBox.Name = "employee_nameTextBox";
			this.employee_nameTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.employee_nameTextBox.TabIndex = 8;
			this.employee_nameTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.employee_nameTextBox_Validating );
			this.Panel1.Controls.Add( this.employee_nameTextBox);
			//
			// employee_surnameLabel
			//
			this.employee_surnameLabel = new System.Windows.Forms.Label();
			this.employee_surnameLabel.AutoSize = true;
			this.employee_surnameLabel.Location = new System.Drawing.Point( 68, 154 );
			this.employee_surnameLabel.Name = "employee_surnameLabel";
			this.employee_surnameLabel.Size = new System.Drawing.Size( 98, 13 );
			this.employee_surnameLabel.TabIndex = 9;
			this.employee_surnameLabel.Text = "employee_surname";
			this.Panel1.Controls.Add( this.employee_surnameLabel );
			//
			// employee_surnameTextBox
			//
			this.employee_surnameTextBox = new System.Windows.Forms.TextBox();
			this.employee_surnameTextBox.Location = new System.Drawing.Point( 176, 154 );
			this.employee_surnameTextBox.Name = "employee_surnameTextBox";
			this.employee_surnameTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.employee_surnameTextBox.TabIndex = 10;
			this.employee_surnameTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.employee_surnameTextBox_Validating );
			this.Panel1.Controls.Add( this.employee_surnameTextBox);
			//
			// employee_emailLabel
			//
			this.employee_emailLabel = new System.Windows.Forms.Label();
			this.employee_emailLabel.AutoSize = true;
			this.employee_emailLabel.Location = new System.Drawing.Point( 84, 180 );
			this.employee_emailLabel.Name = "employee_emailLabel";
			this.employee_emailLabel.Size = new System.Drawing.Size( 82, 13 );
			this.employee_emailLabel.TabIndex = 11;
			this.employee_emailLabel.Text = "employee_email";
			this.Panel1.Controls.Add( this.employee_emailLabel );
			//
			// employee_emailTextBox
			//
			this.employee_emailTextBox = new System.Windows.Forms.TextBox();
			this.employee_emailTextBox.Location = new System.Drawing.Point( 176, 180 );
			this.employee_emailTextBox.Name = "employee_emailTextBox";
			this.employee_emailTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.employee_emailTextBox.TabIndex = 12;
			this.employee_emailTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.employee_emailTextBox_Validating );
			this.Panel1.Controls.Add( this.employee_emailTextBox);
			//
			// employee_displaynameLabel
			//
			this.employee_displaynameLabel = new System.Windows.Forms.Label();
			this.employee_displaynameLabel.AutoSize = true;
			this.employee_displaynameLabel.Location = new System.Drawing.Point( 50, 206 );
			this.employee_displaynameLabel.Name = "employee_displaynameLabel";
			this.employee_displaynameLabel.Size = new System.Drawing.Size( 116, 13 );
			this.employee_displaynameLabel.TabIndex = 13;
			this.employee_displaynameLabel.Text = "employee_displayname";
			this.Panel1.Controls.Add( this.employee_displaynameLabel );
			//
			// employee_displaynameTextBox
			//
			this.employee_displaynameTextBox = new System.Windows.Forms.TextBox();
			this.employee_displaynameTextBox.Location = new System.Drawing.Point( 176, 206 );
			this.employee_displaynameTextBox.Name = "employee_displaynameTextBox";
			this.employee_displaynameTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.employee_displaynameTextBox.TabIndex = 14;
			this.employee_displaynameTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.employee_displaynameTextBox_Validating );
			this.Panel1.Controls.Add( this.employee_displaynameTextBox);
			//
			// employee_phoneLabel
			//
			this.employee_phoneLabel = new System.Windows.Forms.Label();
			this.employee_phoneLabel.AutoSize = true;
			this.employee_phoneLabel.Location = new System.Drawing.Point( 78, 232 );
			this.employee_phoneLabel.Name = "employee_phoneLabel";
			this.employee_phoneLabel.Size = new System.Drawing.Size( 88, 13 );
			this.employee_phoneLabel.TabIndex = 15;
			this.employee_phoneLabel.Text = "employee_phone";
			this.Panel1.Controls.Add( this.employee_phoneLabel );
			//
			// employee_phoneTextBox
			//
			this.employee_phoneTextBox = new System.Windows.Forms.TextBox();
			this.employee_phoneTextBox.Location = new System.Drawing.Point( 176, 232 );
			this.employee_phoneTextBox.Name = "employee_phoneTextBox";
			this.employee_phoneTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.employee_phoneTextBox.TabIndex = 16;
			this.employee_phoneTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.employee_phoneTextBox_Validating );
			this.Panel1.Controls.Add( this.employee_phoneTextBox);
			//
			// employee_mphoneLabel
			//
			this.employee_mphoneLabel = new System.Windows.Forms.Label();
			this.employee_mphoneLabel.AutoSize = true;
			this.employee_mphoneLabel.Location = new System.Drawing.Point( 406, 50 );
			this.employee_mphoneLabel.Name = "employee_mphoneLabel";
			this.employee_mphoneLabel.Size = new System.Drawing.Size( 96, 13 );
			this.employee_mphoneLabel.TabIndex = 17;
			this.employee_mphoneLabel.Text = "employee_mphone";
			this.Panel1.Controls.Add( this.employee_mphoneLabel );
			//
			// employee_mphoneTextBox
			//
			this.employee_mphoneTextBox = new System.Windows.Forms.TextBox();
			this.employee_mphoneTextBox.Location = new System.Drawing.Point( 512, 50 );
			this.employee_mphoneTextBox.Name = "employee_mphoneTextBox";
			this.employee_mphoneTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.employee_mphoneTextBox.TabIndex = 18;
			this.employee_mphoneTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.employee_mphoneTextBox_Validating );
			this.Panel1.Controls.Add( this.employee_mphoneTextBox);
			//
			// employee_wphoneLabel
			//
			this.employee_wphoneLabel = new System.Windows.Forms.Label();
			this.employee_wphoneLabel.AutoSize = true;
			this.employee_wphoneLabel.Location = new System.Drawing.Point( 406, 76 );
			this.employee_wphoneLabel.Name = "employee_wphoneLabel";
			this.employee_wphoneLabel.Size = new System.Drawing.Size( 96, 13 );
			this.employee_wphoneLabel.TabIndex = 19;
			this.employee_wphoneLabel.Text = "employee_wphone";
			this.Panel1.Controls.Add( this.employee_wphoneLabel );
			//
			// employee_wphoneTextBox
			//
			this.employee_wphoneTextBox = new System.Windows.Forms.TextBox();
			this.employee_wphoneTextBox.Location = new System.Drawing.Point( 512, 76 );
			this.employee_wphoneTextBox.Name = "employee_wphoneTextBox";
			this.employee_wphoneTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.employee_wphoneTextBox.TabIndex = 20;
			this.employee_wphoneTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.employee_wphoneTextBox_Validating );
			this.Panel1.Controls.Add( this.employee_wphoneTextBox);
			//
			// employee_faxLabel
			//
			this.employee_faxLabel = new System.Windows.Forms.Label();
			this.employee_faxLabel.AutoSize = true;
			this.employee_faxLabel.Location = new System.Drawing.Point( 430, 102 );
			this.employee_faxLabel.Name = "employee_faxLabel";
			this.employee_faxLabel.Size = new System.Drawing.Size( 72, 13 );
			this.employee_faxLabel.TabIndex = 21;
			this.employee_faxLabel.Text = "employee_fax";
			this.Panel1.Controls.Add( this.employee_faxLabel );
			//
			// employee_faxTextBox
			//
			this.employee_faxTextBox = new System.Windows.Forms.TextBox();
			this.employee_faxTextBox.Location = new System.Drawing.Point( 512, 102 );
			this.employee_faxTextBox.Name = "employee_faxTextBox";
			this.employee_faxTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.employee_faxTextBox.TabIndex = 22;
			this.employee_faxTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.employee_faxTextBox_Validating );
			this.Panel1.Controls.Add( this.employee_faxTextBox);
			//
			// employee_skypeLabel
			//
			this.employee_skypeLabel = new System.Windows.Forms.Label();
			this.employee_skypeLabel.AutoSize = true;
			this.employee_skypeLabel.Location = new System.Drawing.Point( 416, 128 );
			this.employee_skypeLabel.Name = "employee_skypeLabel";
			this.employee_skypeLabel.Size = new System.Drawing.Size( 86, 13 );
			this.employee_skypeLabel.TabIndex = 23;
			this.employee_skypeLabel.Text = "employee_skype";
			this.Panel1.Controls.Add( this.employee_skypeLabel );
			//
			// employee_skypeTextBox
			//
			this.employee_skypeTextBox = new System.Windows.Forms.TextBox();
			this.employee_skypeTextBox.Location = new System.Drawing.Point( 512, 128 );
			this.employee_skypeTextBox.Name = "employee_skypeTextBox";
			this.employee_skypeTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.employee_skypeTextBox.TabIndex = 24;
			this.employee_skypeTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.employee_skypeTextBox_Validating );
			this.Panel1.Controls.Add( this.employee_skypeTextBox);
			//
			// employee_hphoneLabel
			//
			this.employee_hphoneLabel = new System.Windows.Forms.Label();
			this.employee_hphoneLabel.AutoSize = true;
			this.employee_hphoneLabel.Location = new System.Drawing.Point( 408, 154 );
			this.employee_hphoneLabel.Name = "employee_hphoneLabel";
			this.employee_hphoneLabel.Size = new System.Drawing.Size( 94, 13 );
			this.employee_hphoneLabel.TabIndex = 25;
			this.employee_hphoneLabel.Text = "employee_hphone";
			this.Panel1.Controls.Add( this.employee_hphoneLabel );
			//
			// employee_hphoneTextBox
			//
			this.employee_hphoneTextBox = new System.Windows.Forms.TextBox();
			this.employee_hphoneTextBox.Location = new System.Drawing.Point( 512, 154 );
			this.employee_hphoneTextBox.Name = "employee_hphoneTextBox";
			this.employee_hphoneTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.employee_hphoneTextBox.TabIndex = 26;
			this.employee_hphoneTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.employee_hphoneTextBox_Validating );
			this.Panel1.Controls.Add( this.employee_hphoneTextBox);
			//
			// employee_addressLabel
			//
			this.employee_addressLabel = new System.Windows.Forms.Label();
			this.employee_addressLabel.AutoSize = true;
			this.employee_addressLabel.Location = new System.Drawing.Point( 407, 180 );
			this.employee_addressLabel.Name = "employee_addressLabel";
			this.employee_addressLabel.Size = new System.Drawing.Size( 95, 13 );
			this.employee_addressLabel.TabIndex = 27;
			this.employee_addressLabel.Text = "employee_address";
			this.Panel1.Controls.Add( this.employee_addressLabel );
			//
			// employee_addressTextBox
			//
			this.employee_addressTextBox = new System.Windows.Forms.TextBox();
			this.employee_addressTextBox.Location = new System.Drawing.Point( 512, 180 );
			this.employee_addressTextBox.Name = "employee_addressTextBox";
			this.employee_addressTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.employee_addressTextBox.TabIndex = 28;
			this.employee_addressTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.employee_addressTextBox_Validating );
			this.Panel1.Controls.Add( this.employee_addressTextBox);
			//
			// employee_descriptionLabel
			//
			this.employee_descriptionLabel = new System.Windows.Forms.Label();
			this.employee_descriptionLabel.AutoSize = true;
			this.employee_descriptionLabel.Location = new System.Drawing.Point( 393, 206 );
			this.employee_descriptionLabel.Name = "employee_descriptionLabel";
			this.employee_descriptionLabel.Size = new System.Drawing.Size( 109, 13 );
			this.employee_descriptionLabel.TabIndex = 29;
			this.employee_descriptionLabel.Text = "employee_description";
			this.Panel1.Controls.Add( this.employee_descriptionLabel );
			//
			// employee_descriptionTextBox
			//
			this.employee_descriptionTextBox = new System.Windows.Forms.TextBox();
			this.employee_descriptionTextBox.Location = new System.Drawing.Point( 512, 206 );
			this.employee_descriptionTextBox.Name = "employee_descriptionTextBox";
			this.employee_descriptionTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.employee_descriptionTextBox.TabIndex = 30;
			this.employee_descriptionTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.employee_descriptionTextBox_Validating );
			this.Panel1.Controls.Add( this.employee_descriptionTextBox);
			//
			// jobtitle_idLabel
			//
			this.jobtitle_idLabel = new System.Windows.Forms.Label();
			this.jobtitle_idLabel.AutoSize = true;
			this.jobtitle_idLabel.Location = new System.Drawing.Point( 451, 232 );
			this.jobtitle_idLabel.Name = "jobtitle_idLabel";
			this.jobtitle_idLabel.Size = new System.Drawing.Size( 51, 13 );
			this.jobtitle_idLabel.TabIndex = 31;
			this.jobtitle_idLabel.Text = "jobtitle_id";
			this.Panel1.Controls.Add( this.jobtitle_idLabel );
			this.jobtitle_id_comboBox = new System.Windows.Forms.ComboBox();
			this.jobtitle_id_comboBox.Location = new System.Drawing.Point( 512, 232 );
			this.jobtitle_id_comboBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Append;
			this.jobtitle_id_comboBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
			this.jobtitle_id_comboBox.FormattingEnabled = true;
			this.jobtitle_id_comboBox.Name = "jobtitle_id_comboBox";
			this.jobtitle_id_comboBox.Size = new System.Drawing.Size(206, 21);
			this.jobtitle_id_comboBox.TabIndex = 32;
			this.jobtitle_id_comboBox.Validating += new System.ComponentModel.CancelEventHandler( this.jobtitle_id_comboBox_Validating );
			this.Panel1.Controls.Add( this.jobtitle_id_comboBox );
			// 
			// panel4
			// 
			this.panel4.Dock = System.Windows.Forms.DockStyle.Right;
			this.panel4.Location = new System.Drawing.Point(656, 0);
			this.panel4.Name = "panel4";
			this.panel4.Size = new System.Drawing.Size(10, 183);
			this.panel4.TabIndex = 3;
			// 
			// panel3
			// 
			this.panel3.Controls.Add(this.Panel1);
			this.panel3.Controls.Add(this.panel4);
			this.panel3.Controls.Add(this.panel5);
			this.panel3.Controls.Add(this.panel6);
			this.panel3.Dock = System.Windows.Forms.DockStyle.Fill;
			this.panel3.Location = new System.Drawing.Point(0, 25);
			this.panel3.Name = "panel3";
			this.panel3.Size = new System.Drawing.Size(666, 183);
			this.panel3.TabIndex = 19;
			// 
			// panel5
			// 
			this.panel5.Dock = System.Windows.Forms.DockStyle.Left;
			this.panel5.Location = new System.Drawing.Point(0, 0);
			this.panel5.Name = "panel5";
			this.panel5.Size = new System.Drawing.Size(10, 183);
			this.panel5.TabIndex = 5;
			// 
			// panel6
			// 
			this.panel6.Dock = System.Windows.Forms.DockStyle.Bottom;
			this.panel6.Location = new System.Drawing.Point(0, 324);
			this.panel6.Name = "panel6";
			this.panel6.Size = new System.Drawing.Size(400, 10);
			this.panel6.TabIndex = 6;
			
			
			// 
			// frmemployees
			// 
			this.AutoScroll = true;
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(400, 359);
			this.Name = "frmemployees";
			this.Text = "frmemployees";
			this.Load += new System.EventHandler(this.frmemployees_Load);
			this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmemployees_FormClosing);
			((System.ComponentModel.ISupportInitialize)(this.bindingNavigator1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
			this.bindingNavigator1.ResumeLayout(false);
			this.bindingNavigator1.PerformLayout();
			this.Text = "Employees";
			((System.ComponentModel.ISupportInitialize)(this.employeesBindingSource)).EndInit();
			this.Controls.Add(this.panel3);
			this.panel3.ResumeLayout(false);
			this.panel3.PerformLayout();
			
			this.Controls.Add(this.bindingNavigator1);
			this.Panel1.ResumeLayout(false);
			this.Panel1.PerformLayout();
			this.ResumeLayout(false);
			this.PerformLayout();
			
		}
		
		#endregion
		
		private System.Windows.Forms.BindingNavigator bindingNavigator1;
		private System.Windows.Forms.ToolStripButton bindingNavigatorAddNewItem;
		private System.Windows.Forms.ToolStripLabel bindingNavigatorCountItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorDeleteItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveFirstItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMovePreviousItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator;
		private System.Windows.Forms.ToolStripTextBox bindingNavigatorPositionItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator1;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveNextItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveLastItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator2;
		private System.Windows.Forms.ToolStripButton toolStripButton1;
		private System.Windows.Forms.ErrorProvider errorProvider1;
		private System.Windows.Forms.Panel Panel1;
		private System.Windows.Forms.BindingSource employeesBindingSource;
		private System.Windows.Forms.TextBox employee_idTextBox;
		private System.Windows.Forms.Label employee_idLabel;
		private System.Windows.Forms.TextBox employee_loginTextBox;
		private System.Windows.Forms.Label employee_loginLabel;
		private System.Windows.Forms.TextBox employee_passwordTextBox;
		private System.Windows.Forms.Label employee_passwordLabel;
		private System.Windows.Forms.TextBox employee_nameTextBox;
		private System.Windows.Forms.Label employee_nameLabel;
		private System.Windows.Forms.TextBox employee_surnameTextBox;
		private System.Windows.Forms.Label employee_surnameLabel;
		private System.Windows.Forms.TextBox employee_emailTextBox;
		private System.Windows.Forms.Label employee_emailLabel;
		private System.Windows.Forms.TextBox employee_displaynameTextBox;
		private System.Windows.Forms.Label employee_displaynameLabel;
		private System.Windows.Forms.TextBox employee_phoneTextBox;
		private System.Windows.Forms.Label employee_phoneLabel;
		private System.Windows.Forms.TextBox employee_mphoneTextBox;
		private System.Windows.Forms.Label employee_mphoneLabel;
		private System.Windows.Forms.TextBox employee_wphoneTextBox;
		private System.Windows.Forms.Label employee_wphoneLabel;
		private System.Windows.Forms.TextBox employee_faxTextBox;
		private System.Windows.Forms.Label employee_faxLabel;
		private System.Windows.Forms.TextBox employee_skypeTextBox;
		private System.Windows.Forms.Label employee_skypeLabel;
		private System.Windows.Forms.TextBox employee_hphoneTextBox;
		private System.Windows.Forms.Label employee_hphoneLabel;
		private System.Windows.Forms.TextBox employee_addressTextBox;
		private System.Windows.Forms.Label employee_addressLabel;
		private System.Windows.Forms.TextBox employee_descriptionTextBox;
		private System.Windows.Forms.Label employee_descriptionLabel;
		private System.Windows.Forms.ComboBox jobtitle_id_comboBox;
		private System.Windows.Forms.Label jobtitle_idLabel;
		private System.Windows.Forms.Panel panel3;
		private System.Windows.Forms.Panel panel4;
		private System.Windows.Forms.Panel panel5;
		private System.Windows.Forms.Panel panel6;
		
	}
}

