/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using MySql.Data.MySqlClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity;

namespace ArtFlex
{
	public partial class frmorders : Form
	{
		private ModelArtFlexEntities ctx;
		
		public frmorders()
		{
			InitializeComponent();
		}
		
		private void frmorders_Load(object sender, EventArgs e)
		{
			ctx = new ModelArtFlexEntities();
			ctx.orders.Load();
			BindingList<orders> _entities = ctx.orders.Local.ToBindingList();
			ordersBindingSource.DataSource = _entities;
			this.order_idTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.ordersBindingSource, "order_id", true ));
			this.client_idTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.ordersBindingSource, "client_id", true ));
			this.order_statusTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.ordersBindingSource, "order_status", true ));
			this.employee_idTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.ordersBindingSource, "employee_id", true ));
			this.order_createtimeTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.ordersBindingSource, "order_createtime", true ));
			
		}
		
		private void Save_Click(object sender, EventArgs e)
		{
			if (!this.Validate()) return;
			ordersBindingSource.EndEdit();
			ctx.SaveChanges();
			
		}
		
		private void frmorders_FormClosing(object sender, FormClosingEventArgs e)
		{
			e.Cancel = false;
		}
		
		private void order_idTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( order_idTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( order_idTextBox, "The field order_id is required" ); 
			}
			int v;
			string s = order_idTextBox.Text;
			if( !int.TryParse( s, out v ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( order_idTextBox, "The field order_id must be int." );
			}
			if( !e.Cancel ) { errorProvider1.SetError( order_idTextBox, "" ); } 
		}
		
		private void client_idTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( client_idTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( client_idTextBox, "The field client_id is required" ); 
			}
			int v;
			string s = client_idTextBox.Text;
			if( !int.TryParse( s, out v ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( client_idTextBox, "The field client_id must be int." );
			}
			if( !e.Cancel ) { errorProvider1.SetError( client_idTextBox, "" ); } 
		}
		
		private void order_statusTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( order_statusTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( order_statusTextBox, "The field order_status is required" ); 
			}
			int v;
			string s = order_statusTextBox.Text;
			if( !int.TryParse( s, out v ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( order_statusTextBox, "The field order_status must be int." );
			}
			if( !e.Cancel ) { errorProvider1.SetError( order_statusTextBox, "" ); } 
		}
		
		private void employee_idTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( employee_idTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( employee_idTextBox, "The field employee_id is required" ); 
			}
			int v;
			string s = employee_idTextBox.Text;
			if( !int.TryParse( s, out v ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( employee_idTextBox, "The field employee_id must be int." );
			}
			if( !e.Cancel ) { errorProvider1.SetError( employee_idTextBox, "" ); } 
		}
		
		
		
		
		private void bindingNavigatorAddNewItem_Click(object sender, EventArgs e)
		{
			ordersBindingSource.AddNew();
		}
	}
}
