/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

namespace ArtFlex
{
	partial class frmrests
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}
		
		#region Windows Form Designer generated code
		
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.components = new System.ComponentModel.Container();
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmrests));
			this.bindingNavigator1 = new System.Windows.Forms.BindingNavigator(this.components);
			this.bindingNavigatorAddNewItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorCountItem = new System.Windows.Forms.ToolStripLabel();
			this.bindingNavigatorDeleteItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorMoveFirstItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorMovePreviousItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorSeparator = new System.Windows.Forms.ToolStripSeparator();
			this.bindingNavigatorPositionItem = new System.Windows.Forms.ToolStripTextBox();
			this.bindingNavigatorSeparator1 = new System.Windows.Forms.ToolStripSeparator();
			this.bindingNavigatorMoveNextItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorMoveLastItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorSeparator2 = new System.Windows.Forms.ToolStripSeparator();
			this.toolStripButton1 = new System.Windows.Forms.ToolStripButton();
			this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
			
			this.Panel1 = new System.Windows.Forms.Panel();
			
			this.restsBindingSource = new System.Windows.Forms.BindingSource(this.components);
			this.panel3 = new System.Windows.Forms.Panel();
			this.panel4 = new System.Windows.Forms.Panel();
			this.panel5 = new System.Windows.Forms.Panel();
			this.panel6 = new System.Windows.Forms.Panel();
			
			((System.ComponentModel.ISupportInitialize)(this.bindingNavigator1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
			this.bindingNavigator1.SuspendLayout();
			this.panel3.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.restsBindingSource)).BeginInit();
			
			this.Panel1.SuspendLayout();
			this.SuspendLayout();
			// 
			// bindingNavigator1
			// 
			this.bindingNavigator1.AddNewItem = null;
			this.bindingNavigator1.CountItem = this.bindingNavigatorCountItem;
			this.bindingNavigator1.DeleteItem = this.bindingNavigatorDeleteItem;
			this.bindingNavigator1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
			this.bindingNavigatorMoveFirstItem,
			this.bindingNavigatorMovePreviousItem,
			this.bindingNavigatorSeparator,
			this.bindingNavigatorPositionItem,
			this.bindingNavigatorCountItem,
			this.bindingNavigatorSeparator1,
			this.bindingNavigatorMoveNextItem,
			this.bindingNavigatorMoveLastItem,
			this.bindingNavigatorSeparator2,
			this.bindingNavigatorAddNewItem,
			this.bindingNavigatorDeleteItem,
			this.toolStripButton1});
			this.bindingNavigator1.Location = new System.Drawing.Point(0, 0);
			this.bindingNavigator1.MoveFirstItem = this.bindingNavigatorMoveFirstItem;
			this.bindingNavigator1.MoveLastItem = this.bindingNavigatorMoveLastItem;
			this.bindingNavigator1.MoveNextItem = this.bindingNavigatorMoveNextItem;
			this.bindingNavigator1.MovePreviousItem = this.bindingNavigatorMovePreviousItem;
			this.bindingNavigator1.Name = "bindingNavigator1";
			this.bindingNavigator1.Padding = new System.Windows.Forms.Padding(10, 0, 10, 0);
			this.bindingNavigator1.PositionItem = this.bindingNavigatorPositionItem;
			this.bindingNavigator1.Size = new System.Drawing.Size(360, 25);
			this.bindingNavigator1.TabIndex = 0;
			this.bindingNavigator1.Text = "bindingNavigator1";
			// 
			// bindingNavigatorAddNewItem
			// 
			this.bindingNavigatorAddNewItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorAddNewItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorAddNewItem.Image")));
			this.bindingNavigatorAddNewItem.Name = "bindingNavigatorAddNewItem";
			this.bindingNavigatorAddNewItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorAddNewItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorAddNewItem.Text = "Add new";
			this.bindingNavigatorAddNewItem.Click += new System.EventHandler(this.bindingNavigatorAddNewItem_Click);
			// 
			// bindingNavigatorCountItem
			// 
			this.bindingNavigatorCountItem.Name = "bindingNavigatorCountItem";
			this.bindingNavigatorCountItem.Size = new System.Drawing.Size(35, 22);
			this.bindingNavigatorCountItem.Text = "of {0}";
			this.bindingNavigatorCountItem.ToolTipText = "Total number of items";
			// 
			// bindingNavigatorDeleteItem
			// 
			this.bindingNavigatorDeleteItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorDeleteItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorDeleteItem.Image")));
			this.bindingNavigatorDeleteItem.Name = "bindingNavigatorDeleteItem";
			this.bindingNavigatorDeleteItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorDeleteItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorDeleteItem.Text = "Delete";
			// 
			// bindingNavigatorMoveFirstItem
			// 
			this.bindingNavigatorMoveFirstItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorMoveFirstItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveFirstItem.Image")));
			this.bindingNavigatorMoveFirstItem.Name = "bindingNavigatorMoveFirstItem";
			this.bindingNavigatorMoveFirstItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorMoveFirstItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorMoveFirstItem.Text = "Move first";
			// 
			// bindingNavigatorMovePreviousItem
			// 
			this.bindingNavigatorMovePreviousItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorMovePreviousItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMovePreviousItem.Image")));
			this.bindingNavigatorMovePreviousItem.Name = "bindingNavigatorMovePreviousItem";
			this.bindingNavigatorMovePreviousItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorMovePreviousItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorMovePreviousItem.Text = "Move previous";
			// 
			// bindingNavigatorSeparator
			// 
			this.bindingNavigatorSeparator.Name = "bindingNavigatorSeparator";
			this.bindingNavigatorSeparator.Size = new System.Drawing.Size(6, 25);
			// 
			// bindingNavigatorPositionItem
			// 
			this.bindingNavigatorPositionItem.AccessibleName = "Position";
			this.bindingNavigatorPositionItem.AutoSize = false;
			this.bindingNavigatorPositionItem.Name = "bindingNavigatorPositionItem";
			this.bindingNavigatorPositionItem.Size = new System.Drawing.Size(50, 23);
			this.bindingNavigatorPositionItem.Text = "0";
			this.bindingNavigatorPositionItem.ToolTipText = "Current position";
			// 
			// bindingNavigatorSeparator1
			// 
			this.bindingNavigatorSeparator1.Name = "bindingNavigatorSeparator1";
			this.bindingNavigatorSeparator1.Size = new System.Drawing.Size(6, 25);
			// 
			// bindingNavigatorMoveNextItem
			// 
			this.bindingNavigatorMoveNextItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorMoveNextItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveNextItem.Image")));
			this.bindingNavigatorMoveNextItem.Name = "bindingNavigatorMoveNextItem";
			this.bindingNavigatorMoveNextItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorMoveNextItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorMoveNextItem.Text = "Move next";
			// 
			// bindingNavigatorMoveLastItem
			// 
			this.bindingNavigatorMoveLastItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorMoveLastItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveLastItem.Image")));
			this.bindingNavigatorMoveLastItem.Name = "bindingNavigatorMoveLastItem";
			this.bindingNavigatorMoveLastItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorMoveLastItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorMoveLastItem.Text = "Move last";
			// 
			// bindingNavigatorSeparator2
			// 
			this.bindingNavigatorSeparator2.Name = "bindingNavigatorSeparator2";
			this.bindingNavigatorSeparator2.Size = new System.Drawing.Size(6, 25);
			// 
			// toolStripButton1
			// 
			this.toolStripButton1.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.toolStripButton1.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorSaveItem.Image")));
			this.toolStripButton1.ImageTransparentColor = System.Drawing.Color.Magenta;
			this.toolStripButton1.Name = "toolStripButton1";
			this.toolStripButton1.Size = new System.Drawing.Size(23, 22);
			this.toolStripButton1.Text = "Save";
			this.toolStripButton1.Click += new System.EventHandler(this.Save_Click);
			// 
			// errorProvider1
			// 
			this.errorProvider1.ContainerControl = this;
			//
			// Panel1
			//
			this.Panel1.AutoScroll = true;
			this.Panel1.Dock = System.Windows.Forms.DockStyle.Fill;
			this.Panel1.Location = new System.Drawing.Point(0, 25);
			this.Panel1.Margin = new System.Windows.Forms.Padding(10, 3, 10, 3);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new System.Drawing.Size(656, 183);
			this.Panel1.TabIndex = 1;
			this.Panel1.AutoSize = true;
			
			this.bindingNavigator1.BindingSource = this.restsBindingSource;
			//
			// rest_idLabel
			//
			this.rest_idLabel = new System.Windows.Forms.Label();
			this.rest_idLabel.AutoSize = true;
			this.rest_idLabel.Location = new System.Drawing.Point( 91, 50 );
			this.rest_idLabel.Name = "rest_idLabel";
			this.rest_idLabel.Size = new System.Drawing.Size( 38, 13 );
			this.rest_idLabel.TabIndex = 1;
			this.rest_idLabel.Text = "rest_id";
			this.Panel1.Controls.Add( this.rest_idLabel );
			//
			// rest_idTextBox
			//
			this.rest_idTextBox = new System.Windows.Forms.TextBox();
			this.rest_idTextBox.Location = new System.Drawing.Point( 139, 50 );
			this.rest_idTextBox.Name = "rest_idTextBox";
			this.rest_idTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.rest_idTextBox.TabIndex = 2;
			this.rest_idTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.rest_idTextBox_Validating );
			this.Panel1.Controls.Add( this.rest_idTextBox);
			//
			// supply_idLabel
			//
			this.supply_idLabel = new System.Windows.Forms.Label();
			this.supply_idLabel.AutoSize = true;
			this.supply_idLabel.Location = new System.Drawing.Point( 78, 76 );
			this.supply_idLabel.Name = "supply_idLabel";
			this.supply_idLabel.Size = new System.Drawing.Size( 51, 13 );
			this.supply_idLabel.TabIndex = 3;
			this.supply_idLabel.Text = "supply_id";
			this.Panel1.Controls.Add( this.supply_idLabel );
			this.supply_id_comboBox = new System.Windows.Forms.ComboBox();
			this.supply_id_comboBox.Location = new System.Drawing.Point( 139, 76 );
			this.supply_id_comboBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Append;
			this.supply_id_comboBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
			this.supply_id_comboBox.FormattingEnabled = true;
			this.supply_id_comboBox.Name = "supply_id_comboBox";
			this.supply_id_comboBox.Size = new System.Drawing.Size(206, 21);
			this.supply_id_comboBox.TabIndex = 4;
			this.supply_id_comboBox.Validating += new System.ComponentModel.CancelEventHandler( this.supply_id_comboBox_Validating );
			this.Panel1.Controls.Add( this.supply_id_comboBox );
			//
			// material_idLabel
			//
			this.material_idLabel = new System.Windows.Forms.Label();
			this.material_idLabel.AutoSize = true;
			this.material_idLabel.Location = new System.Drawing.Point( 72, 102 );
			this.material_idLabel.Name = "material_idLabel";
			this.material_idLabel.Size = new System.Drawing.Size( 57, 13 );
			this.material_idLabel.TabIndex = 5;
			this.material_idLabel.Text = "material_id";
			this.Panel1.Controls.Add( this.material_idLabel );
			this.material_id_comboBox = new System.Windows.Forms.ComboBox();
			this.material_id_comboBox.Location = new System.Drawing.Point( 139, 102 );
			this.material_id_comboBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Append;
			this.material_id_comboBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
			this.material_id_comboBox.FormattingEnabled = true;
			this.material_id_comboBox.Name = "material_id_comboBox";
			this.material_id_comboBox.Size = new System.Drawing.Size(206, 21);
			this.material_id_comboBox.TabIndex = 6;
			this.material_id_comboBox.Validating += new System.ComponentModel.CancelEventHandler( this.material_id_comboBox_Validating );
			this.Panel1.Controls.Add( this.material_id_comboBox );
			//
			// rest_quantityLabel
			//
			this.rest_quantityLabel = new System.Windows.Forms.Label();
			this.rest_quantityLabel.AutoSize = true;
			this.rest_quantityLabel.Location = new System.Drawing.Point( 361, 50 );
			this.rest_quantityLabel.Name = "rest_quantityLabel";
			this.rest_quantityLabel.Size = new System.Drawing.Size( 67, 13 );
			this.rest_quantityLabel.TabIndex = 7;
			this.rest_quantityLabel.Text = "rest_quantity";
			this.Panel1.Controls.Add( this.rest_quantityLabel );
			//
			// rest_quantityTextBox
			//
			this.rest_quantityTextBox = new System.Windows.Forms.TextBox();
			this.rest_quantityTextBox.Location = new System.Drawing.Point( 438, 50 );
			this.rest_quantityTextBox.Name = "rest_quantityTextBox";
			this.rest_quantityTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.rest_quantityTextBox.TabIndex = 8;
			this.rest_quantityTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.rest_quantityTextBox_Validating );
			this.Panel1.Controls.Add( this.rest_quantityTextBox);
			//
			// rest_summLabel
			//
			this.rest_summLabel = new System.Windows.Forms.Label();
			this.rest_summLabel.AutoSize = true;
			this.rest_summLabel.Location = new System.Drawing.Point( 371, 76 );
			this.rest_summLabel.Name = "rest_summLabel";
			this.rest_summLabel.Size = new System.Drawing.Size( 57, 13 );
			this.rest_summLabel.TabIndex = 9;
			this.rest_summLabel.Text = "rest_summ";
			this.Panel1.Controls.Add( this.rest_summLabel );
			//
			// rest_summTextBox
			//
			this.rest_summTextBox = new System.Windows.Forms.TextBox();
			this.rest_summTextBox.Location = new System.Drawing.Point( 438, 76 );
			this.rest_summTextBox.Name = "rest_summTextBox";
			this.rest_summTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.rest_summTextBox.TabIndex = 10;
			this.rest_summTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.rest_summTextBox_Validating );
			this.Panel1.Controls.Add( this.rest_summTextBox);
			//
			// rest_dateLabel
			//
			this.rest_dateLabel = new System.Windows.Forms.Label();
			this.rest_dateLabel.AutoSize = true;
			this.rest_dateLabel.Location = new System.Drawing.Point( 377, 102 );
			this.rest_dateLabel.Name = "rest_dateLabel";
			this.rest_dateLabel.Size = new System.Drawing.Size( 51, 13 );
			this.rest_dateLabel.TabIndex = 11;
			this.rest_dateLabel.Text = "rest_date";
			this.Panel1.Controls.Add( this.rest_dateLabel );
			//
			// rest_date_dateTimePicker
			//
			this.rest_date_dateTimePicker = new System.Windows.Forms.DateTimePicker();
			this.rest_date_dateTimePicker.CustomFormat = "dd/MM/yyyy"; 
			this.rest_date_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
			this.rest_date_dateTimePicker.Location = new System.Drawing.Point(438, 102);
			this.rest_date_dateTimePicker.Name = "rest_date_dateTimePicker";
			this.rest_date_dateTimePicker.Size = new System.Drawing.Size(200, 20);
			this.rest_date_dateTimePicker.TabIndex = 12;
			this.rest_date_dateTimePicker.Value = new System.DateTime(2014, 5, 26, 17, 35, 11, 0);
			this.Panel1.Controls.Add( this.rest_date_dateTimePicker );
			//
			// rest_createtimeLabel
			//
			this.rest_createtimeLabel = new System.Windows.Forms.Label();
			this.rest_createtimeLabel.AutoSize = true;
			this.rest_createtimeLabel.Location = new System.Drawing.Point( 349, 128 );
			this.rest_createtimeLabel.Name = "rest_createtimeLabel";
			this.rest_createtimeLabel.Size = new System.Drawing.Size( 79, 13 );
			this.rest_createtimeLabel.TabIndex = 13;
			this.rest_createtimeLabel.Text = "rest_createtime";
			this.Panel1.Controls.Add( this.rest_createtimeLabel );
			//
			// rest_createtimeTextBox
			//
			this.rest_createtimeTextBox = new System.Windows.Forms.TextBox();
			this.rest_createtimeTextBox.Location = new System.Drawing.Point( 438, 128 );
			this.rest_createtimeTextBox.Name = "rest_createtimeTextBox";
			this.rest_createtimeTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.rest_createtimeTextBox.TabIndex = 14;
			this.rest_createtimeTextBox.Enabled = false;
			this.Panel1.Controls.Add( this.rest_createtimeTextBox);
			// 
			// panel4
			// 
			this.panel4.Dock = System.Windows.Forms.DockStyle.Right;
			this.panel4.Location = new System.Drawing.Point(656, 0);
			this.panel4.Name = "panel4";
			this.panel4.Size = new System.Drawing.Size(10, 183);
			this.panel4.TabIndex = 3;
			// 
			// panel3
			// 
			this.panel3.Controls.Add(this.Panel1);
			this.panel3.Controls.Add(this.panel4);
			this.panel3.Controls.Add(this.panel5);
			this.panel3.Controls.Add(this.panel6);
			this.panel3.Dock = System.Windows.Forms.DockStyle.Fill;
			this.panel3.Location = new System.Drawing.Point(0, 25);
			this.panel3.Name = "panel3";
			this.panel3.Size = new System.Drawing.Size(666, 183);
			this.panel3.TabIndex = 19;
			// 
			// panel5
			// 
			this.panel5.Dock = System.Windows.Forms.DockStyle.Left;
			this.panel5.Location = new System.Drawing.Point(0, 0);
			this.panel5.Name = "panel5";
			this.panel5.Size = new System.Drawing.Size(10, 183);
			this.panel5.TabIndex = 5;
			// 
			// panel6
			// 
			this.panel6.Dock = System.Windows.Forms.DockStyle.Bottom;
			this.panel6.Location = new System.Drawing.Point(0, 324);
			this.panel6.Name = "panel6";
			this.panel6.Size = new System.Drawing.Size(400, 10);
			this.panel6.TabIndex = 6;
			
			
			// 
			// frmrests
			// 
			this.AutoScroll = true;
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(400, 359);
			this.Name = "frmrests";
			this.Text = "frmrests";
			this.Load += new System.EventHandler(this.frmrests_Load);
			this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmrests_FormClosing);
			((System.ComponentModel.ISupportInitialize)(this.bindingNavigator1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
			this.bindingNavigator1.ResumeLayout(false);
			this.bindingNavigator1.PerformLayout();
			this.Text = "Rests";
			((System.ComponentModel.ISupportInitialize)(this.restsBindingSource)).EndInit();
			this.Controls.Add(this.panel3);
			this.panel3.ResumeLayout(false);
			this.panel3.PerformLayout();
			
			this.Controls.Add(this.bindingNavigator1);
			this.Panel1.ResumeLayout(false);
			this.Panel1.PerformLayout();
			this.ResumeLayout(false);
			this.PerformLayout();
			
		}
		
		#endregion
		
		private System.Windows.Forms.BindingNavigator bindingNavigator1;
		private System.Windows.Forms.ToolStripButton bindingNavigatorAddNewItem;
		private System.Windows.Forms.ToolStripLabel bindingNavigatorCountItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorDeleteItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveFirstItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMovePreviousItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator;
		private System.Windows.Forms.ToolStripTextBox bindingNavigatorPositionItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator1;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveNextItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveLastItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator2;
		private System.Windows.Forms.ToolStripButton toolStripButton1;
		private System.Windows.Forms.ErrorProvider errorProvider1;
		private System.Windows.Forms.Panel Panel1;
		private System.Windows.Forms.BindingSource restsBindingSource;
		private System.Windows.Forms.TextBox rest_idTextBox;
		private System.Windows.Forms.Label rest_idLabel;
		private System.Windows.Forms.ComboBox supply_id_comboBox;
		private System.Windows.Forms.Label supply_idLabel;
		private System.Windows.Forms.ComboBox material_id_comboBox;
		private System.Windows.Forms.Label material_idLabel;
		private System.Windows.Forms.TextBox rest_quantityTextBox;
		private System.Windows.Forms.Label rest_quantityLabel;
		private System.Windows.Forms.TextBox rest_summTextBox;
		private System.Windows.Forms.Label rest_summLabel;
		private System.Windows.Forms.DateTimePicker rest_date_dateTimePicker;
		private System.Windows.Forms.Label rest_dateLabel;
		private System.Windows.Forms.TextBox rest_createtimeTextBox;
		private System.Windows.Forms.Label rest_createtimeLabel;
		private System.Windows.Forms.Panel panel3;
		private System.Windows.Forms.Panel panel4;
		private System.Windows.Forms.Panel panel5;
		private System.Windows.Forms.Panel panel6;
		
	}
}

