/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using MySql.Data.MySqlClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity;
using MySqlDB;
using System.Reflection;

namespace ArtFlex
{
	public partial class frmsupplier : Form
	{
		private ArtflexDbContext context;
		
		public frmsupplier()
		{
			InitializeComponent();
		}

        /// <summary>
        /// Изменение свойства DoubleBuffered контрола.
        /// </summary>
        /// <param name="c">Ссылка на контрол.</param>
        /// <param name="value">Значение, которое надо установить DoubleBuffered.</param>
        void SetDoubleBuffered(Control c, bool value)
        {
            PropertyInfo pi = typeof(Control).GetProperty("DoubleBuffered", BindingFlags.SetProperty | BindingFlags.Instance | BindingFlags.NonPublic);
            if (pi != null)
            {
                pi.SetValue(c, value, null);

                MethodInfo mi = typeof(Control).GetMethod("SetStyle", BindingFlags.Instance | BindingFlags.InvokeMethod | BindingFlags.NonPublic);
                if (mi != null)
                {
                    mi.Invoke(c, new object[] { ControlStyles.UserPaint | ControlStyles.AllPaintingInWmPaint | ControlStyles.OptimizedDoubleBuffer, true });
                }

                mi = typeof(Control).GetMethod("UpdateStyles", BindingFlags.Instance | BindingFlags.InvokeMethod | BindingFlags.NonPublic);
                if (mi != null)
                {
                    mi.Invoke(c, null);
                }
            }
        }
		
		private void frmsupplier_Load(object sender, EventArgs e)
		{
			context = new ArtflexDbContext();
			context.suppliers.Load();
			BindingList<suppliers> _entities = context.suppliers.Local.ToBindingList();
			suppliersBindingSource.DataSource = _entities;
			this.supplier_nameTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.suppliersBindingSource, "supplier_name", true ));
			this.supplier_emailTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.suppliersBindingSource, "supplier_email", true ));
			this.supplier_wphoneTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.suppliersBindingSource, "supplier_wphone", true ));
			this.supplier_faxTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.suppliersBindingSource, "supplier_fax", true ));
			this.supplier_skipeTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.suppliersBindingSource, "supplier_skipe", true ));
			this.supplier_addressTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.suppliersBindingSource, "supplier_address", true ));
			this.supplier_descriptionTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.suppliersBindingSource, "supplier_description", true ));

            // DataGridView Collumns
            System.Windows.Forms.DataGridViewTextBoxColumn col_supplier_id = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_supplier_id.DataPropertyName = "supplier_id";
            col_supplier_id.HeaderText = "ID";
            col_supplier_id.Name = "col_supplier_id";
            dataGridViewSuppliers.Columns.Add(col_supplier_id);

            System.Windows.Forms.DataGridViewTextBoxColumn col_supplier_name = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_supplier_name.DataPropertyName = "supplier_name";
            col_supplier_name.HeaderText = "Имя";
            col_supplier_name.Name = "col_supplier_name";
            dataGridViewSuppliers.Columns.Add(col_supplier_name);

            System.Windows.Forms.DataGridViewTextBoxColumn col_supplier_email = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_supplier_email.DataPropertyName = "supplier_email";
            col_supplier_email.HeaderText = "e-mail";
            col_supplier_email.Name = "col_supplier_email";
            dataGridViewSuppliers.Columns.Add(col_supplier_email);


            System.Windows.Forms.DataGridViewTextBoxColumn col_supplier_wphone = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_supplier_wphone.DataPropertyName = "supplier_wphone";
            col_supplier_wphone.HeaderText = "Телефон";
            col_supplier_wphone.Name = "col_supplier_wphone";
            dataGridViewSuppliers.Columns.Add(col_supplier_wphone);

            System.Windows.Forms.DataGridViewTextBoxColumn col_supplier_fax = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_supplier_fax.DataPropertyName = "supplier_fax";
            col_supplier_fax.HeaderText = "Факс";
            col_supplier_fax.Name = "col_supplier_fax";
            dataGridViewSuppliers.Columns.Add(col_supplier_fax);

            System.Windows.Forms.DataGridViewTextBoxColumn col_supplier_skipe = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_supplier_skipe.DataPropertyName = "supplier_skipe";
            col_supplier_skipe.HeaderText = "Скайп";
            col_supplier_skipe.Name = "col_supplier_skipe";
            dataGridViewSuppliers.Columns.Add(col_supplier_skipe);

            System.Windows.Forms.DataGridViewTextBoxColumn col_supplier_address = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_supplier_address.DataPropertyName = "supplier_address";
            col_supplier_address.HeaderText = "Адрес";
            col_supplier_address.Name = "col_supplier_address";
            dataGridViewSuppliers.Columns.Add(col_supplier_address);

            System.Windows.Forms.DataGridViewTextBoxColumn col_supplier_description = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_supplier_description.DataPropertyName = "supplier_description";
            col_supplier_description.HeaderText = "Описание";
            col_supplier_description.Name = "col_supplier_description";
            dataGridViewSuppliers.Columns.Add(col_supplier_description);


            this.dataGridViewSuppliers.AutoGenerateColumns = false;
            this.dataGridViewSuppliers.DataSource = this.suppliersBindingSource;

            SetDoubleBuffered(dataGridViewSuppliers, true);

            this.splitContainer1.SplitterDistance = 120;

            this.buttonCancel.CausesValidation = false;		
		}
		
		private void Save_Click(object sender, EventArgs e)
		{
			if (!this.Validate()) return;
			suppliersBindingSource.EndEdit();
			context.SaveChanges();
			
		}
		
		private void frmsupplier_FormClosing(object sender, FormClosingEventArgs e)
		{
			e.Cancel = false;
		}

		
		private void supplier_nameTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( supplier_nameTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( supplier_nameTextBox, "The field supplier_name is required" ); 
			}
			if( !e.Cancel ) { errorProvider1.SetError( supplier_nameTextBox, "" ); } 
		}
		
		
		private void supplier_emailTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
            //if( string.IsNullOrEmpty( supplier_emailTextBox.Text ) )
            //{
            //    e.Cancel = true;
            //    errorProvider1.SetError( supplier_emailTextBox, "The field supplier_email is required" ); 
            //}
            //if( !e.Cancel ) { errorProvider1.SetError( supplier_emailTextBox, "" ); } 
		}

		private void supplier_wphoneTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
        //    if( string.IsNullOrEmpty( supplier_wphoneTextBox.Text ) )
        //    {
        //        e.Cancel = true;
        //        errorProvider1.SetError( supplier_wphoneTextBox, "The field supplier_wphone is required" ); 
        //    }
        //    if( !e.Cancel ) { errorProvider1.SetError( supplier_wphoneTextBox, "" ); } 
        }
		
		private void supplier_faxTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
            //if( string.IsNullOrEmpty( supplier_faxTextBox.Text ) )
            //{
            //    e.Cancel = true;
            //    errorProvider1.SetError( supplier_faxTextBox, "The field supplier_fax is required" ); 
            //}
            //if( !e.Cancel ) { errorProvider1.SetError( supplier_faxTextBox, "" ); } 
		}
		
		private void supplier_skipeTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
            //if( string.IsNullOrEmpty( supplier_skipeTextBox.Text ) )
            //{
            //    e.Cancel = true;
            //    errorProvider1.SetError( supplier_skipeTextBox, "The field supplier_skipe is required" ); 
            //}
            //if( !e.Cancel ) { errorProvider1.SetError( supplier_skipeTextBox, "" ); } 
		}
		
		private void supplier_addressTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
            //if( string.IsNullOrEmpty( supplier_addressTextBox.Text ) )
            //{
            //    e.Cancel = true;
            //    errorProvider1.SetError( supplier_addressTextBox, "The field supplier_address is required" ); 
            //}
            //if( !e.Cancel ) { errorProvider1.SetError( supplier_addressTextBox, "" ); } 
		}
		
		private void supplier_descriptionTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
            //if( string.IsNullOrEmpty( supplier_descriptionTextBox.Text ) )
            //{
            //    e.Cancel = true;
            //    errorProvider1.SetError( supplier_descriptionTextBox, "The field supplier_description is required" ); 
            //}
            //if( !e.Cancel ) { errorProvider1.SetError( supplier_descriptionTextBox, "" ); } 
		}
		
	}
}
