/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

namespace ArtFlex
{
	partial class frmsupply
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}
		
		#region Windows Form Designer generated code
		
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.components = new System.ComponentModel.Container();
            this.suppliesBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
            this.Panel1 = new System.Windows.Forms.Panel();
            this.supply_idLabel = new System.Windows.Forms.Label();
            this.supply_idTextBox = new System.Windows.Forms.TextBox();
            this.supply_quantityLabel = new System.Windows.Forms.Label();
            this.supply_quantityTextBox = new System.Windows.Forms.TextBox();
            this.material_idLabel = new System.Windows.Forms.Label();
            this.material_idTextBox = new System.Windows.Forms.TextBox();
            this.supply_summLabel = new System.Windows.Forms.Label();
            this.supply_summTextBox = new System.Windows.Forms.TextBox();
            this.supply_costunitLabel = new System.Windows.Forms.Label();
            this.supply_costunitTextBox = new System.Windows.Forms.TextBox();
            this.supply_descriptionLabel = new System.Windows.Forms.Label();
            this.supply_descriptionTextBox = new System.Windows.Forms.TextBox();
            this.waybill_idLabel = new System.Windows.Forms.Label();
            this.waybill_idTextBox = new System.Windows.Forms.TextBox();
            this.supply_createtimeLabel = new System.Windows.Forms.Label();
            this.supply_createtimeTextBox = new System.Windows.Forms.TextBox();
            ((System.ComponentModel.ISupportInitialize)(this.suppliesBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
            this.Panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // errorProvider1
            // 
            this.errorProvider1.ContainerControl = this;
            // 
            // Panel1
            // 
            this.Panel1.AutoScroll = true;
            this.Panel1.AutoSize = true;
            this.Panel1.Controls.Add(this.supply_idLabel);
            this.Panel1.Controls.Add(this.supply_idTextBox);
            this.Panel1.Controls.Add(this.supply_quantityLabel);
            this.Panel1.Controls.Add(this.supply_quantityTextBox);
            this.Panel1.Controls.Add(this.material_idLabel);
            this.Panel1.Controls.Add(this.material_idTextBox);
            this.Panel1.Controls.Add(this.supply_summLabel);
            this.Panel1.Controls.Add(this.supply_summTextBox);
            this.Panel1.Controls.Add(this.supply_costunitLabel);
            this.Panel1.Controls.Add(this.supply_costunitTextBox);
            this.Panel1.Controls.Add(this.supply_descriptionLabel);
            this.Panel1.Controls.Add(this.supply_descriptionTextBox);
            this.Panel1.Controls.Add(this.waybill_idLabel);
            this.Panel1.Controls.Add(this.waybill_idTextBox);
            this.Panel1.Controls.Add(this.supply_createtimeLabel);
            this.Panel1.Controls.Add(this.supply_createtimeTextBox);
            this.Panel1.Location = new System.Drawing.Point(158, 281);
            this.Panel1.Margin = new System.Windows.Forms.Padding(10, 3, 10, 3);
            this.Panel1.Name = "Panel1";
            this.Panel1.Size = new System.Drawing.Size(656, 183);
            this.Panel1.TabIndex = 1;
            // 
            // supply_idLabel
            // 
            this.supply_idLabel.AutoSize = true;
            this.supply_idLabel.Location = new System.Drawing.Point(93, 50);
            this.supply_idLabel.Name = "supply_idLabel";
            this.supply_idLabel.Size = new System.Drawing.Size(51, 13);
            this.supply_idLabel.TabIndex = 1;
            this.supply_idLabel.Text = "supply_id";
            // 
            // supply_idTextBox
            // 
            this.supply_idTextBox.Location = new System.Drawing.Point(154, 50);
            this.supply_idTextBox.Name = "supply_idTextBox";
            this.supply_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.supply_idTextBox.TabIndex = 2;
            this.supply_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.supply_idTextBox_Validating);
            // 
            // supply_quantityLabel
            // 
            this.supply_quantityLabel.AutoSize = true;
            this.supply_quantityLabel.Location = new System.Drawing.Point(64, 76);
            this.supply_quantityLabel.Name = "supply_quantityLabel";
            this.supply_quantityLabel.Size = new System.Drawing.Size(80, 13);
            this.supply_quantityLabel.TabIndex = 3;
            this.supply_quantityLabel.Text = "supply_quantity";
            // 
            // supply_quantityTextBox
            // 
            this.supply_quantityTextBox.Location = new System.Drawing.Point(154, 76);
            this.supply_quantityTextBox.Name = "supply_quantityTextBox";
            this.supply_quantityTextBox.Size = new System.Drawing.Size(100, 20);
            this.supply_quantityTextBox.TabIndex = 4;
            this.supply_quantityTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.supply_quantityTextBox_Validating);
            // 
            // material_idLabel
            // 
            this.material_idLabel.AutoSize = true;
            this.material_idLabel.Location = new System.Drawing.Point(87, 102);
            this.material_idLabel.Name = "material_idLabel";
            this.material_idLabel.Size = new System.Drawing.Size(57, 13);
            this.material_idLabel.TabIndex = 5;
            this.material_idLabel.Text = "material_id";
            // 
            // material_idTextBox
            // 
            this.material_idTextBox.Location = new System.Drawing.Point(154, 102);
            this.material_idTextBox.Name = "material_idTextBox";
            this.material_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.material_idTextBox.TabIndex = 6;
            this.material_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.material_idTextBox_Validating);
            // 
            // supply_summLabel
            // 
            this.supply_summLabel.AutoSize = true;
            this.supply_summLabel.Location = new System.Drawing.Point(74, 128);
            this.supply_summLabel.Name = "supply_summLabel";
            this.supply_summLabel.Size = new System.Drawing.Size(70, 13);
            this.supply_summLabel.TabIndex = 7;
            this.supply_summLabel.Text = "supply_summ";
            // 
            // supply_summTextBox
            // 
            this.supply_summTextBox.Location = new System.Drawing.Point(154, 128);
            this.supply_summTextBox.Name = "supply_summTextBox";
            this.supply_summTextBox.Size = new System.Drawing.Size(100, 20);
            this.supply_summTextBox.TabIndex = 8;
            this.supply_summTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.supply_summTextBox_Validating);
            // 
            // supply_costunitLabel
            // 
            this.supply_costunitLabel.AutoSize = true;
            this.supply_costunitLabel.Location = new System.Drawing.Point(378, 50);
            this.supply_costunitLabel.Name = "supply_costunitLabel";
            this.supply_costunitLabel.Size = new System.Drawing.Size(80, 13);
            this.supply_costunitLabel.TabIndex = 9;
            this.supply_costunitLabel.Text = "supply_costunit";
            // 
            // supply_costunitTextBox
            // 
            this.supply_costunitTextBox.Location = new System.Drawing.Point(468, 50);
            this.supply_costunitTextBox.Name = "supply_costunitTextBox";
            this.supply_costunitTextBox.Size = new System.Drawing.Size(100, 20);
            this.supply_costunitTextBox.TabIndex = 10;
            this.supply_costunitTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.supply_costunitTextBox_Validating);
            // 
            // supply_descriptionLabel
            // 
            this.supply_descriptionLabel.AutoSize = true;
            this.supply_descriptionLabel.Location = new System.Drawing.Point(364, 76);
            this.supply_descriptionLabel.Name = "supply_descriptionLabel";
            this.supply_descriptionLabel.Size = new System.Drawing.Size(94, 13);
            this.supply_descriptionLabel.TabIndex = 11;
            this.supply_descriptionLabel.Text = "supply_description";
            // 
            // supply_descriptionTextBox
            // 
            this.supply_descriptionTextBox.Location = new System.Drawing.Point(468, 76);
            this.supply_descriptionTextBox.Name = "supply_descriptionTextBox";
            this.supply_descriptionTextBox.Size = new System.Drawing.Size(100, 20);
            this.supply_descriptionTextBox.TabIndex = 12;
            this.supply_descriptionTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.supply_descriptionTextBox_Validating);
            // 
            // waybill_idLabel
            // 
            this.waybill_idLabel.AutoSize = true;
            this.waybill_idLabel.Location = new System.Drawing.Point(406, 102);
            this.waybill_idLabel.Name = "waybill_idLabel";
            this.waybill_idLabel.Size = new System.Drawing.Size(52, 13);
            this.waybill_idLabel.TabIndex = 13;
            this.waybill_idLabel.Text = "waybill_id";
            // 
            // waybill_idTextBox
            // 
            this.waybill_idTextBox.Location = new System.Drawing.Point(468, 102);
            this.waybill_idTextBox.Name = "waybill_idTextBox";
            this.waybill_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.waybill_idTextBox.TabIndex = 14;
            this.waybill_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.waybill_idTextBox_Validating);
            // 
            // supply_createtimeLabel
            // 
            this.supply_createtimeLabel.AutoSize = true;
            this.supply_createtimeLabel.Location = new System.Drawing.Point(366, 128);
            this.supply_createtimeLabel.Name = "supply_createtimeLabel";
            this.supply_createtimeLabel.Size = new System.Drawing.Size(92, 13);
            this.supply_createtimeLabel.TabIndex = 15;
            this.supply_createtimeLabel.Text = "supply_createtime";
            // 
            // supply_createtimeTextBox
            // 
            this.supply_createtimeTextBox.Enabled = false;
            this.supply_createtimeTextBox.Location = new System.Drawing.Point(468, 128);
            this.supply_createtimeTextBox.Name = "supply_createtimeTextBox";
            this.supply_createtimeTextBox.Size = new System.Drawing.Size(100, 20);
            this.supply_createtimeTextBox.TabIndex = 16;
            // 
            // frmsupply
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoScroll = true;
            this.ClientSize = new System.Drawing.Size(1450, 687);
            this.Controls.Add(this.Panel1);
            this.Name = "frmsupply";
            this.Text = "Supply";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmsupply_FormClosing);
            this.Load += new System.EventHandler(this.frmsupply_Load);
            ((System.ComponentModel.ISupportInitialize)(this.suppliesBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
            this.Panel1.ResumeLayout(false);
            this.Panel1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

		}
		
		#endregion

        private System.Windows.Forms.ErrorProvider errorProvider1;
		private System.Windows.Forms.Panel Panel1;
		private System.Windows.Forms.BindingSource suppliesBindingSource;
		private System.Windows.Forms.TextBox supply_idTextBox;
		private System.Windows.Forms.Label supply_idLabel;
		private System.Windows.Forms.TextBox supply_quantityTextBox;
		private System.Windows.Forms.Label supply_quantityLabel;
		private System.Windows.Forms.TextBox material_idTextBox;
		private System.Windows.Forms.Label material_idLabel;
		private System.Windows.Forms.TextBox supply_summTextBox;
		private System.Windows.Forms.Label supply_summLabel;
		private System.Windows.Forms.TextBox supply_costunitTextBox;
		private System.Windows.Forms.Label supply_costunitLabel;
		private System.Windows.Forms.TextBox supply_descriptionTextBox;
		private System.Windows.Forms.Label supply_descriptionLabel;
		private System.Windows.Forms.TextBox waybill_idTextBox;
		private System.Windows.Forms.Label waybill_idLabel;
		private System.Windows.Forms.TextBox supply_createtimeTextBox;
        private System.Windows.Forms.Label supply_createtimeLabel;
		
	}
}

