/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using MySql.Data.MySqlClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity;
using MySqlDB;
using System.Reflection;

namespace ArtFlex
{
    public partial class frmsupplies : Form
    {
        private ArtflexDbContext context;

        public frmsupplies()
        {
            InitializeComponent();
        }


        /// <summary>
        /// Изменение свойства DoubleBuffered контрола.
        /// </summary>
        /// <param name="c">Ссылка на контрол.</param>
        /// <param name="value">Значение, которое надо установить DoubleBuffered.</param>
        void SetDoubleBuffered(Control c, bool value)
        {
            PropertyInfo pi = typeof(Control).GetProperty("DoubleBuffered", BindingFlags.SetProperty | BindingFlags.Instance | BindingFlags.NonPublic);
            if (pi != null)
            {
                pi.SetValue(c, value, null);

                MethodInfo mi = typeof(Control).GetMethod("SetStyle", BindingFlags.Instance | BindingFlags.InvokeMethod | BindingFlags.NonPublic);
                if (mi != null)
                {
                    mi.Invoke(c, new object[] { ControlStyles.UserPaint | ControlStyles.AllPaintingInWmPaint | ControlStyles.OptimizedDoubleBuffer, true });
                }

                mi = typeof(Control).GetMethod("UpdateStyles", BindingFlags.Instance | BindingFlags.InvokeMethod | BindingFlags.NonPublic);
                if (mi != null)
                {
                    mi.Invoke(c, null);
                }
            }
        }

        private void frmsupply_Load(object sender, EventArgs e)
        {
            context = new ArtflexDbContext();
            context.Configuration.ProxyCreationEnabled = false; 

            context.categories.Load();
            BindingList<categories> _categories = context.categories.Local.ToBindingList();
            categoriesBindingSource.DataSource = _categories;

            context.supplies.Load();
            BindingList<supplies> _supplies = context.supplies.Local.ToBindingList();
            suppliesBindingSource.DataSource = _supplies;
                
            context.waybills.Load();
            BindingList<waybills> _waybills = context.waybills.Local.ToBindingList();
            waybillsBindingSource.DataSource = _waybills;


            this.waybill_nameTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.waybillsBindingSource, "waybill_name", true));
            this.waybill_date_dateTimePicker.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.waybillsBindingSource, "waybill_date", true));

            // Supplier selector
            this.supplierComboBox.DataSource = context.suppliers.ToList();
            this.supplierComboBox.DisplayMember = "supplier_name";
            this.supplierComboBox.ValueMember = "supplier_id";

            // Categories selector
            this.categoriesComboBox.DataSource = categoriesBindingSource;
            this.categoriesComboBox.DisplayMember = "category_name";
            this.categoriesComboBox.ValueMember = "category_id";

            // dataGridViewSupplies Collumns
            System.Windows.Forms.DataGridViewTextBoxColumn col_supply_id = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_supply_id.DataPropertyName = "supply_id";
            col_supply_id.HeaderText = "ID";
            col_supply_id.Name = "col_supply_id";
            dataGridViewSupplies.Columns.Add(col_supply_id);

            System.Windows.Forms.DataGridViewComboBoxColumn col_material = new System.Windows.Forms.DataGridViewComboBoxColumn();
            col_material.DataSource = context.materials.ToList();
            col_material.DataPropertyName = "material_id";
            col_material.DisplayMember = "material_name";
            col_material.ValueMember = "material_id";
            col_material.HeaderText = "Материал";
            col_material.Name = "col_material";
            col_material.DisplayStyle = DataGridViewComboBoxDisplayStyle.Nothing;
            dataGridViewSupplies.Columns.Add(col_material);

            System.Windows.Forms.DataGridViewTextBoxColumn col_supply_quantity = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_supply_quantity.DataPropertyName = "supply_quantity";
            col_supply_quantity.HeaderText = "Кличество";
            col_supply_quantity.Name = "col_supply_quantity";
            dataGridViewSupplies.Columns.Add(col_supply_quantity);

            System.Windows.Forms.DataGridViewTextBoxColumn col_supply_summ = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_supply_summ.Name = "col_supply_summ";
            col_supply_summ.HeaderText = "Сумма";
            col_supply_summ.DataPropertyName = "supply_summ";
            dataGridViewSupplies.Columns.Add(col_supply_summ);

            System.Windows.Forms.DataGridViewTextBoxColumn col_supply_costunit = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_supply_costunit.Name = "col_supply_costunit";
            col_supply_costunit.HeaderText = "Цена за единицу";
            col_supply_costunit.DataPropertyName = "supply_costunit";
            dataGridViewSupplies.Columns.Add(col_supply_costunit);

            System.Windows.Forms.DataGridViewTextBoxColumn col_supply_description = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_supply_description.Name = "col_supply_description";
            col_supply_description.HeaderText = "Примечание";
            col_supply_description.DataPropertyName = "supply_description";
            dataGridViewSupplies.Columns.Add(col_supply_description);

            //System.Windows.Forms.DataGridViewComboBoxColumn col_waybill_id = new System.Windows.Forms.DataGridViewComboBoxColumn();
            //col_waybill_id.DataSource = context.waybills.ToList();
            //col_waybill_id.DataPropertyName = "waybill_id";
            //col_waybill_id.DisplayMember = "waybill_name";
            //col_waybill_id.ValueMember = "waybill_id";
            //col_waybill_id.HeaderText = "Накладная";
            //col_waybill_id.Name = "col_waybill_id";
            //col_waybill_id.DisplayStyle = DataGridViewComboBoxDisplayStyle.Nothing;
            //dataGridViewSupplies.Columns.Add(col_waybill_id);

            System.Windows.Forms.DataGridViewTextBoxColumn col_suppy_date = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_suppy_date.Name = "col_suppy_date";
            col_suppy_date.HeaderText = "Дата поставки";
            col_suppy_date.DataPropertyName = "suppy_date";
            dataGridViewSupplies.Columns.Add(col_suppy_date);

            this.dataGridViewSupplies.AutoGenerateColumns = false;
            this.dataGridViewSupplies.DataSource = this.suppliesBindingSource;



            // dataGridViewMaterials
            System.Windows.Forms.DataGridViewTextBoxColumn col_material_id = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_material_id.DataPropertyName = "material_id";
            col_material_id.HeaderText = "ID";
            col_material_id.Name = "col_material_id";
            dataGridViewMaterials.Columns.Add(col_material_id);

            System.Windows.Forms.DataGridViewComboBoxColumn col_category_id = new System.Windows.Forms.DataGridViewComboBoxColumn();
            col_category_id.DataSource = context.categories.ToList();
            col_category_id.DataPropertyName = "category_id";
            col_category_id.DisplayMember = "category_name";
            col_category_id.ValueMember = "category_id";
            col_category_id.HeaderText = "Тип";
            col_category_id.Name = "col_category_id";
            col_category_id.DisplayStyle = DataGridViewComboBoxDisplayStyle.Nothing;
            dataGridViewMaterials.Columns.Add(col_category_id);

            System.Windows.Forms.DataGridViewTextBoxColumn col_material_name = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_material_name.DataPropertyName = "material_name";
            col_material_name.HeaderText = "Название материала";
            col_material_name.Name = "col_material_name";
            dataGridViewMaterials.Columns.Add(col_material_name);

            System.Windows.Forms.DataGridViewComboBoxColumn col_units_id = new DataGridViewComboBoxColumn();
            col_units_id.DataSource = context.units.ToList();
            col_units_id.DataPropertyName = "unit_id";
            col_units_id.DisplayMember = "unit_shortname";
            col_units_id.ValueMember = "unit_id";
            col_units_id.HeaderText = "Ед. изм.";
            col_units_id.Name = "col_units_id";
            col_units_id.DisplayStyle = DataGridViewComboBoxDisplayStyle.Nothing;
            dataGridViewMaterials.Columns.Add(col_units_id);

            System.Windows.Forms.DataGridViewTextBoxColumn col_material_size = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_material_size.Name = "col_material_size";
            col_material_size.HeaderText = "Размер";
            col_material_size.DataPropertyName = "material_size";
            dataGridViewMaterials.Columns.Add(col_material_size);

            System.Windows.Forms.DataGridViewTextBoxColumn col_material_rollwidth = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_material_rollwidth.DataPropertyName = "material_rollwidth";
            col_material_rollwidth.HeaderText = "Ширина рулона";
            col_material_rollwidth.Name = "col_material_rollwidth";
            dataGridViewMaterials.Columns.Add(col_material_rollwidth);

            System.Windows.Forms.DataGridViewTextBoxColumn col_material_description = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_material_description.Name = "col_material_description";
            col_material_description.HeaderText = "Описание";
            col_material_description.DataPropertyName = "material_description";
            col_material_description.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            dataGridViewMaterials.Columns.Add(col_material_description);

            System.Windows.Forms.DataGridViewTextBoxColumn col_material_createtime = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_material_createtime.Name = "col_material_createtime";
            col_material_createtime.HeaderText = "Дата добавления";
            col_material_createtime.DataPropertyName = "material_createtime";
            col_material_createtime.ReadOnly = true;
            dataGridViewMaterials.Columns.Add(col_material_createtime);

            this.dataGridViewMaterials.AutoGenerateColumns = false;
            this.dataGridViewMaterials.DataSource = this.materialsBindingSource;


            // DoubleBuffered
            SetDoubleBuffered(dataGridViewSupplies, true);
            SetDoubleBuffered(dataGridViewMaterials, true);


            this.buttonCancel.CausesValidation = false;

            this.waybill_date_dateTimePicker.Value = DateTime.Now;

        }

        private void frmsupply_FormClosing(object sender, FormClosingEventArgs e)
        {
            e.Cancel = false;
        }

        #region Validating
        private void supply_quantityTextBox_Validating(object sender, CancelEventArgs e)
        {
            e.Cancel = false;
            //if( string.IsNullOrEmpty( supply_quantityTextBox.Text ) )
            //{
            //    e.Cancel = true;
            //    errorProvider1.SetError( supply_quantityTextBox, "The field supply_quantity is required" ); 
            //}
            //double v;
            //string s = supply_quantityTextBox.Text;
            //if( !double.TryParse( s, out v ) )
            //{
            //    e.Cancel = true;
            //    errorProvider1.SetError( supply_quantityTextBox, "The field supply_quantity must be double." );
            //}
            //if( !e.Cancel ) { errorProvider1.SetError( supply_quantityTextBox, "" ); } 
        }

        private void supply_summTextBox_Validating(object sender, CancelEventArgs e)
        {
            e.Cancel = false;
            //if( string.IsNullOrEmpty( supply_summTextBox.Text ) )
            //{
            //    e.Cancel = true;
            //    errorProvider1.SetError( supply_summTextBox, "The field supply_summ is required" ); 
            //}
            //double v;
            //string s = supply_summTextBox.Text;
            //if( !double.TryParse( s, out v ) )
            //{
            //    e.Cancel = true;
            //    errorProvider1.SetError( supply_summTextBox, "The field supply_summ must be double." );
            //}
            //if( !e.Cancel ) { errorProvider1.SetError( supply_summTextBox, "" ); } 
        }

        private void supply_costunitTextBox_Validating(object sender, CancelEventArgs e)
        {
            e.Cancel = false;
            //if( string.IsNullOrEmpty( supply_costunitTextBox.Text ) )
            //{
            //    e.Cancel = true;
            //    errorProvider1.SetError( supply_costunitTextBox, "The field supply_costunit is required" ); 
            //}
            //double v;
            //string s = supply_costunitTextBox.Text;
            //if( !double.TryParse( s, out v ) )
            //{
            //    e.Cancel = true;
            //    errorProvider1.SetError( supply_costunitTextBox, "The field supply_costunit must be double." );
            //}
            //if( !e.Cancel ) { errorProvider1.SetError( supply_costunitTextBox, "" ); } 
        }

        private void supply_descriptionTextBox_Validating(object sender, CancelEventArgs e)
        {
            e.Cancel = false;
            //if( string.IsNullOrEmpty( supply_descriptionTextBox.Text ) )
            //{
            //    e.Cancel = true;
            //    errorProvider1.SetError( supply_descriptionTextBox, "The field supply_description is required" ); 
            //}
            //if( !e.Cancel ) { errorProvider1.SetError( supply_descriptionTextBox, "" ); } 
        }

        private void waybill_idTextBox_Validating(object sender, CancelEventArgs e)
        {
            e.Cancel = false;
            //if( string.IsNullOrEmpty( waybill_idTextBox.Text ) )
            //{
            //    e.Cancel = true;
            //    errorProvider1.SetError( waybill_idTextBox, "The field waybill_id is required" ); 
            //}
            //int v;
            //string s = waybill_idTextBox.Text;
            //if( !int.TryParse( s, out v ) )
            //{
            //    e.Cancel = true;
            //    errorProvider1.SetError( waybill_idTextBox, "The field waybill_id must be int." );
            //}
            //if( !e.Cancel ) { errorProvider1.SetError( waybill_idTextBox, "" ); } 
        }

        #endregion

        private void categoriesComboBox_SelectedIndexChanged(object sender, EventArgs e)
        {
            //categories category = categoriesComboBox.SelectedItem as categories;
            //if (category == null)
            //    return;

            //this.context.Dispose();
            //this.context = new ArtflexDbContext();
            //this.context.materials.Where<materials>(b => b.category_id == category.category_id).Load();
            //BindingList<materials> _materials = this.context.materials.Local.ToBindingList();
            //materialsBindingSource.DataSource = _materials;
            dataGridViewMaterials.Refresh();
        }

        private void buttonAddNew_Click(object sender, EventArgs e)
        {
            waybillsBindingSource.AddNew();

            //suppliesBindingSource.DataSource = ((waybills)waybillsBindingSource.Current);
            //suppliesBindingSource.DataMember = "supplies";
            //dataGridViewSupplies.Refresh();

            //this.context.Dispose();
            //this.context = new ArtflexDbContext();

            //this.context.supplies.Where<supplies>(s => s.waybill_id == 0).Load();
            //BindingList<waybills> _waybills = this.context.waybills.Local.ToBindingList();
            //suppliesBindingSource.ResetBindings(true);
            //suppliesBindingSource.DataSource = _waybills;
        }

        private void dataGridViewMaterials_CellDoubleClick(object sender, DataGridViewCellEventArgs e)
        {
            //waybillsBindingSource.MoveLast();
            //waybills waybillsObj = waybillsBindingSource.Current as waybills;
            //materials materialsObj = materialsBindingSource.Current as materials;

            //waybillsObj.supplies.Add(new supplies()
            //{
            //    material_id = materialsObj.material_id,
            //    waybill_id = 0
   
            //});

            //suppliesBindingSource.DataSource = waybillsBindingSource.Current;
            //suppliesBindingSource.DataMember = "supplies";
            //dataGridViewSupplies.Refresh();
   
            ////suppliesBindingSource.Add(suppliesObj);
            ////suppliesBindingSource.ResetBindings(true);
            ////suppliesBindingSource.DataSource = waybillsObj.supplies.ToList();
            ////suppliesBindingSource.DataMember = "supplies";
            ////dataGridViewSupplies.Refresh();



            waybillsBindingSource.MoveLast();
            waybills waybillsObj = waybillsBindingSource.Current as waybills;
            materials materialsObj = materialsBindingSource.Current as materials;
            supplies suppliesObj = new supplies()
            {
                materials = materialsObj,
                waybills = waybillsObj
            };

            suppliesBindingSource.Add(suppliesObj);
            dataGridViewSupplies.Refresh();


        }


        private void waybillsBindingSource_CurrentChanged(object sender, EventArgs e)
        {
            suppliesBindingSource.DataSource = waybillsBindingSource.Current;
            suppliesBindingSource.DataMember = "supplies";
            dataGridViewSupplies.Refresh();
        }


        private void categoriesBindingSource_CurrentChanged(object sender, EventArgs e)
        {
            materialsBindingSource.DataSource = categoriesBindingSource.Current;
            materialsBindingSource.DataMember = "materials";
            dataGridViewMaterials.Refresh();
        }
    }
}

