/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using MySql.Data.MySqlClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity;
using MySqlDB;

namespace ArtFlex
{
	public partial class frmsupply : Form
	{
		private ArtflexDbContext context;
		
		public frmsupply()
		{
			InitializeComponent();
		}
		
		private void frmsupply_Load(object sender, EventArgs e)
		{
			context = new ArtflexDbContext();
			context.supplies.Load();
			BindingList<supplies> _entities = context.supplies.Local.ToBindingList();
			supplyBindingSource.DataSource = _entities;
			this.supply_idTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.supplyBindingSource, "supply_id", true ));
			this.supply_quantityTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.supplyBindingSource, "", true ));
			this.material_idTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.supplyBindingSource, "material_id", true ));
			this.supply_summTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.supplyBindingSource, "", true ));
			this.supply_costunitTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.supplyBindingSource, "", true ));
			this.supply_descriptionTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.supplyBindingSource, "supply_description", true ));
			this.waybill_idTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.supplyBindingSource, "waybill_id", true ));
			this.supply_createtimeTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.supplyBindingSource, "supply_createtime", true ));
			
		}
		
		private void Save_Click(object sender, EventArgs e)
		{
			if (!this.Validate()) return;
			supplyBindingSource.EndEdit();
			context.SaveChanges();
			
		}
		
		private void frmsupply_FormClosing(object sender, FormClosingEventArgs e)
		{
			e.Cancel = false;
		}
		
		private void supply_idTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( supply_idTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( supply_idTextBox, "The field supply_id is required" ); 
			}
			int v;
			string s = supply_idTextBox.Text;
			if( !int.TryParse( s, out v ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( supply_idTextBox, "The field supply_id must be int." );
			}
			if( !e.Cancel ) { errorProvider1.SetError( supply_idTextBox, "" ); } 
		}
		
		private void supply_quantityTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( supply_quantityTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( supply_quantityTextBox, "The field supply_quantity is required" ); 
			}
			double v;
			string s = supply_quantityTextBox.Text;
			if( !double.TryParse( s, out v ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( supply_quantityTextBox, "The field supply_quantity must be double." );
			}
			if( !e.Cancel ) { errorProvider1.SetError( supply_quantityTextBox, "" ); } 
		}
		
		private void material_idTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( material_idTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( material_idTextBox, "The field material_id is required" ); 
			}
			int v;
			string s = material_idTextBox.Text;
			if( !int.TryParse( s, out v ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( material_idTextBox, "The field material_id must be int." );
			}
			if( !e.Cancel ) { errorProvider1.SetError( material_idTextBox, "" ); } 
		}
		
		private void supply_summTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( supply_summTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( supply_summTextBox, "The field supply_summ is required" ); 
			}
			double v;
			string s = supply_summTextBox.Text;
			if( !double.TryParse( s, out v ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( supply_summTextBox, "The field supply_summ must be double." );
			}
			if( !e.Cancel ) { errorProvider1.SetError( supply_summTextBox, "" ); } 
		}
		
		private void supply_costunitTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( supply_costunitTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( supply_costunitTextBox, "The field supply_costunit is required" ); 
			}
			double v;
			string s = supply_costunitTextBox.Text;
			if( !double.TryParse( s, out v ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( supply_costunitTextBox, "The field supply_costunit must be double." );
			}
			if( !e.Cancel ) { errorProvider1.SetError( supply_costunitTextBox, "" ); } 
		}
		
		private void supply_descriptionTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( supply_descriptionTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( supply_descriptionTextBox, "The field supply_description is required" ); 
			}
			if( !e.Cancel ) { errorProvider1.SetError( supply_descriptionTextBox, "" ); } 
		}
		
		private void waybill_idTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( waybill_idTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( waybill_idTextBox, "The field waybill_id is required" ); 
			}
			int v;
			string s = waybill_idTextBox.Text;
			if( !int.TryParse( s, out v ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( waybill_idTextBox, "The field waybill_id must be int." );
			}
			if( !e.Cancel ) { errorProvider1.SetError( waybill_idTextBox, "" ); } 
		}
		
		
		
		
		private void bindingNavigatorAddNewItem_Click(object sender, EventArgs e)
		{
			supplyBindingSource.AddNew();
		}
	}
}
