/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

namespace ArtFlex
{
	partial class frmsupplier
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}
		
		#region Windows Form Designer generated code
		
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.components = new System.ComponentModel.Container();
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmsupplier));
			this.bindingNavigator1 = new System.Windows.Forms.BindingNavigator(this.components);
			this.bindingNavigatorAddNewItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorCountItem = new System.Windows.Forms.ToolStripLabel();
			this.bindingNavigatorDeleteItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorMoveFirstItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorMovePreviousItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorSeparator = new System.Windows.Forms.ToolStripSeparator();
			this.bindingNavigatorPositionItem = new System.Windows.Forms.ToolStripTextBox();
			this.bindingNavigatorSeparator1 = new System.Windows.Forms.ToolStripSeparator();
			this.bindingNavigatorMoveNextItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorMoveLastItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorSeparator2 = new System.Windows.Forms.ToolStripSeparator();
			this.toolStripButton1 = new System.Windows.Forms.ToolStripButton();
			this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
			
			this.Panel1 = new System.Windows.Forms.Panel();
			
			this.supplierBindingSource = new System.Windows.Forms.BindingSource(this.components);
			this.panel3 = new System.Windows.Forms.Panel();
			this.panel4 = new System.Windows.Forms.Panel();
			this.panel5 = new System.Windows.Forms.Panel();
			this.panel6 = new System.Windows.Forms.Panel();
			
			((System.ComponentModel.ISupportInitialize)(this.bindingNavigator1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
			this.bindingNavigator1.SuspendLayout();
			this.panel3.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.supplierBindingSource)).BeginInit();
			
			this.Panel1.SuspendLayout();
			this.SuspendLayout();
			// 
			// bindingNavigator1
			// 
			this.bindingNavigator1.AddNewItem = null;
			this.bindingNavigator1.CountItem = this.bindingNavigatorCountItem;
			this.bindingNavigator1.DeleteItem = this.bindingNavigatorDeleteItem;
			this.bindingNavigator1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
			this.bindingNavigatorMoveFirstItem,
			this.bindingNavigatorMovePreviousItem,
			this.bindingNavigatorSeparator,
			this.bindingNavigatorPositionItem,
			this.bindingNavigatorCountItem,
			this.bindingNavigatorSeparator1,
			this.bindingNavigatorMoveNextItem,
			this.bindingNavigatorMoveLastItem,
			this.bindingNavigatorSeparator2,
			this.bindingNavigatorAddNewItem,
			this.bindingNavigatorDeleteItem,
			this.toolStripButton1});
			this.bindingNavigator1.Location = new System.Drawing.Point(0, 0);
			this.bindingNavigator1.MoveFirstItem = this.bindingNavigatorMoveFirstItem;
			this.bindingNavigator1.MoveLastItem = this.bindingNavigatorMoveLastItem;
			this.bindingNavigator1.MoveNextItem = this.bindingNavigatorMoveNextItem;
			this.bindingNavigator1.MovePreviousItem = this.bindingNavigatorMovePreviousItem;
			this.bindingNavigator1.Name = "bindingNavigator1";
			this.bindingNavigator1.Padding = new System.Windows.Forms.Padding(10, 0, 10, 0);
			this.bindingNavigator1.PositionItem = this.bindingNavigatorPositionItem;
			this.bindingNavigator1.Size = new System.Drawing.Size(360, 25);
			this.bindingNavigator1.TabIndex = 0;
			this.bindingNavigator1.Text = "bindingNavigator1";
			// 
			// bindingNavigatorAddNewItem
			// 
			this.bindingNavigatorAddNewItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorAddNewItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorAddNewItem.Image")));
			this.bindingNavigatorAddNewItem.Name = "bindingNavigatorAddNewItem";
			this.bindingNavigatorAddNewItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorAddNewItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorAddNewItem.Text = "Add new";
			this.bindingNavigatorAddNewItem.Click += new System.EventHandler(this.bindingNavigatorAddNewItem_Click);
			// 
			// bindingNavigatorCountItem
			// 
			this.bindingNavigatorCountItem.Name = "bindingNavigatorCountItem";
			this.bindingNavigatorCountItem.Size = new System.Drawing.Size(35, 22);
			this.bindingNavigatorCountItem.Text = "of {0}";
			this.bindingNavigatorCountItem.ToolTipText = "Total number of items";
			// 
			// bindingNavigatorDeleteItem
			// 
			this.bindingNavigatorDeleteItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorDeleteItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorDeleteItem.Image")));
			this.bindingNavigatorDeleteItem.Name = "bindingNavigatorDeleteItem";
			this.bindingNavigatorDeleteItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorDeleteItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorDeleteItem.Text = "Delete";
			// 
			// bindingNavigatorMoveFirstItem
			// 
			this.bindingNavigatorMoveFirstItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorMoveFirstItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveFirstItem.Image")));
			this.bindingNavigatorMoveFirstItem.Name = "bindingNavigatorMoveFirstItem";
			this.bindingNavigatorMoveFirstItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorMoveFirstItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorMoveFirstItem.Text = "Move first";
			// 
			// bindingNavigatorMovePreviousItem
			// 
			this.bindingNavigatorMovePreviousItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorMovePreviousItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMovePreviousItem.Image")));
			this.bindingNavigatorMovePreviousItem.Name = "bindingNavigatorMovePreviousItem";
			this.bindingNavigatorMovePreviousItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorMovePreviousItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorMovePreviousItem.Text = "Move previous";
			// 
			// bindingNavigatorSeparator
			// 
			this.bindingNavigatorSeparator.Name = "bindingNavigatorSeparator";
			this.bindingNavigatorSeparator.Size = new System.Drawing.Size(6, 25);
			// 
			// bindingNavigatorPositionItem
			// 
			this.bindingNavigatorPositionItem.AccessibleName = "Position";
			this.bindingNavigatorPositionItem.AutoSize = false;
			this.bindingNavigatorPositionItem.Name = "bindingNavigatorPositionItem";
			this.bindingNavigatorPositionItem.Size = new System.Drawing.Size(50, 23);
			this.bindingNavigatorPositionItem.Text = "0";
			this.bindingNavigatorPositionItem.ToolTipText = "Current position";
			// 
			// bindingNavigatorSeparator1
			// 
			this.bindingNavigatorSeparator1.Name = "bindingNavigatorSeparator1";
			this.bindingNavigatorSeparator1.Size = new System.Drawing.Size(6, 25);
			// 
			// bindingNavigatorMoveNextItem
			// 
			this.bindingNavigatorMoveNextItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorMoveNextItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveNextItem.Image")));
			this.bindingNavigatorMoveNextItem.Name = "bindingNavigatorMoveNextItem";
			this.bindingNavigatorMoveNextItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorMoveNextItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorMoveNextItem.Text = "Move next";
			// 
			// bindingNavigatorMoveLastItem
			// 
			this.bindingNavigatorMoveLastItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorMoveLastItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveLastItem.Image")));
			this.bindingNavigatorMoveLastItem.Name = "bindingNavigatorMoveLastItem";
			this.bindingNavigatorMoveLastItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorMoveLastItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorMoveLastItem.Text = "Move last";
			// 
			// bindingNavigatorSeparator2
			// 
			this.bindingNavigatorSeparator2.Name = "bindingNavigatorSeparator2";
			this.bindingNavigatorSeparator2.Size = new System.Drawing.Size(6, 25);
			// 
			// toolStripButton1
			// 
			this.toolStripButton1.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.toolStripButton1.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorSaveItem.Image")));
			this.toolStripButton1.ImageTransparentColor = System.Drawing.Color.Magenta;
			this.toolStripButton1.Name = "toolStripButton1";
			this.toolStripButton1.Size = new System.Drawing.Size(23, 22);
			this.toolStripButton1.Text = "Save";
			this.toolStripButton1.Click += new System.EventHandler(this.Save_Click);
			// 
			// errorProvider1
			// 
			this.errorProvider1.ContainerControl = this;
			//
			// Panel1
			//
			this.Panel1.AutoScroll = true;
			this.Panel1.Dock = System.Windows.Forms.DockStyle.Fill;
			this.Panel1.Location = new System.Drawing.Point(0, 25);
			this.Panel1.Margin = new System.Windows.Forms.Padding(10, 3, 10, 3);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new System.Drawing.Size(656, 183);
			this.Panel1.TabIndex = 1;
			this.Panel1.AutoSize = true;
			
			this.bindingNavigator1.BindingSource = this.supplierBindingSource;
			//
			// supplier_idLabel
			//
			this.supplier_idLabel = new System.Windows.Forms.Label();
			this.supplier_idLabel.AutoSize = true;
			this.supplier_idLabel.Location = new System.Drawing.Point( 99, 50 );
			this.supplier_idLabel.Name = "supplier_idLabel";
			this.supplier_idLabel.Size = new System.Drawing.Size( 57, 13 );
			this.supplier_idLabel.TabIndex = 1;
			this.supplier_idLabel.Text = "supplier_id";
			this.Panel1.Controls.Add( this.supplier_idLabel );
			//
			// supplier_idTextBox
			//
			this.supplier_idTextBox = new System.Windows.Forms.TextBox();
			this.supplier_idTextBox.Location = new System.Drawing.Point( 166, 50 );
			this.supplier_idTextBox.Name = "supplier_idTextBox";
			this.supplier_idTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.supplier_idTextBox.TabIndex = 2;
			this.supplier_idTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.supplier_idTextBox_Validating );
			this.Panel1.Controls.Add( this.supplier_idTextBox);
			//
			// supplier_nameLabel
			//
			this.supplier_nameLabel = new System.Windows.Forms.Label();
			this.supplier_nameLabel.AutoSize = true;
			this.supplier_nameLabel.Location = new System.Drawing.Point( 81, 76 );
			this.supplier_nameLabel.Name = "supplier_nameLabel";
			this.supplier_nameLabel.Size = new System.Drawing.Size( 75, 13 );
			this.supplier_nameLabel.TabIndex = 3;
			this.supplier_nameLabel.Text = "supplier_name";
			this.Panel1.Controls.Add( this.supplier_nameLabel );
			//
			// supplier_nameTextBox
			//
			this.supplier_nameTextBox = new System.Windows.Forms.TextBox();
			this.supplier_nameTextBox.Location = new System.Drawing.Point( 166, 76 );
			this.supplier_nameTextBox.Name = "supplier_nameTextBox";
			this.supplier_nameTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.supplier_nameTextBox.TabIndex = 4;
			this.supplier_nameTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.supplier_nameTextBox_Validating );
			this.Panel1.Controls.Add( this.supplier_nameTextBox);
			//
			// supplier_surnameLabel
			//
			this.supplier_surnameLabel = new System.Windows.Forms.Label();
			this.supplier_surnameLabel.AutoSize = true;
			this.supplier_surnameLabel.Location = new System.Drawing.Point( 67, 102 );
			this.supplier_surnameLabel.Name = "supplier_surnameLabel";
			this.supplier_surnameLabel.Size = new System.Drawing.Size( 89, 13 );
			this.supplier_surnameLabel.TabIndex = 5;
			this.supplier_surnameLabel.Text = "supplier_surname";
			this.Panel1.Controls.Add( this.supplier_surnameLabel );
			//
			// supplier_surnameTextBox
			//
			this.supplier_surnameTextBox = new System.Windows.Forms.TextBox();
			this.supplier_surnameTextBox.Location = new System.Drawing.Point( 166, 102 );
			this.supplier_surnameTextBox.Name = "supplier_surnameTextBox";
			this.supplier_surnameTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.supplier_surnameTextBox.TabIndex = 6;
			this.supplier_surnameTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.supplier_surnameTextBox_Validating );
			this.Panel1.Controls.Add( this.supplier_surnameTextBox);
			//
			// supplier_jobtitleLabel
			//
			this.supplier_jobtitleLabel = new System.Windows.Forms.Label();
			this.supplier_jobtitleLabel.AutoSize = true;
			this.supplier_jobtitleLabel.Location = new System.Drawing.Point( 77, 128 );
			this.supplier_jobtitleLabel.Name = "supplier_jobtitleLabel";
			this.supplier_jobtitleLabel.Size = new System.Drawing.Size( 79, 13 );
			this.supplier_jobtitleLabel.TabIndex = 7;
			this.supplier_jobtitleLabel.Text = "supplier_jobtitle";
			this.Panel1.Controls.Add( this.supplier_jobtitleLabel );
			//
			// supplier_jobtitleTextBox
			//
			this.supplier_jobtitleTextBox = new System.Windows.Forms.TextBox();
			this.supplier_jobtitleTextBox.Location = new System.Drawing.Point( 166, 128 );
			this.supplier_jobtitleTextBox.Name = "supplier_jobtitleTextBox";
			this.supplier_jobtitleTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.supplier_jobtitleTextBox.TabIndex = 8;
			this.supplier_jobtitleTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.supplier_jobtitleTextBox_Validating );
			this.Panel1.Controls.Add( this.supplier_jobtitleTextBox);
			//
			// supplier_organisationLabel
			//
			this.supplier_organisationLabel = new System.Windows.Forms.Label();
			this.supplier_organisationLabel.AutoSize = true;
			this.supplier_organisationLabel.Location = new System.Drawing.Point( 50, 154 );
			this.supplier_organisationLabel.Name = "supplier_organisationLabel";
			this.supplier_organisationLabel.Size = new System.Drawing.Size( 106, 13 );
			this.supplier_organisationLabel.TabIndex = 9;
			this.supplier_organisationLabel.Text = "supplier_organisation";
			this.Panel1.Controls.Add( this.supplier_organisationLabel );
			//
			// supplier_organisationTextBox
			//
			this.supplier_organisationTextBox = new System.Windows.Forms.TextBox();
			this.supplier_organisationTextBox.Location = new System.Drawing.Point( 166, 154 );
			this.supplier_organisationTextBox.Name = "supplier_organisationTextBox";
			this.supplier_organisationTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.supplier_organisationTextBox.TabIndex = 10;
			this.supplier_organisationTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.supplier_organisationTextBox_Validating );
			this.Panel1.Controls.Add( this.supplier_organisationTextBox);
			//
			// supplier_emailLabel
			//
			this.supplier_emailLabel = new System.Windows.Forms.Label();
			this.supplier_emailLabel.AutoSize = true;
			this.supplier_emailLabel.Location = new System.Drawing.Point( 83, 180 );
			this.supplier_emailLabel.Name = "supplier_emailLabel";
			this.supplier_emailLabel.Size = new System.Drawing.Size( 73, 13 );
			this.supplier_emailLabel.TabIndex = 11;
			this.supplier_emailLabel.Text = "supplier_email";
			this.Panel1.Controls.Add( this.supplier_emailLabel );
			//
			// supplier_emailTextBox
			//
			this.supplier_emailTextBox = new System.Windows.Forms.TextBox();
			this.supplier_emailTextBox.Location = new System.Drawing.Point( 166, 180 );
			this.supplier_emailTextBox.Name = "supplier_emailTextBox";
			this.supplier_emailTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.supplier_emailTextBox.TabIndex = 12;
			this.supplier_emailTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.supplier_emailTextBox_Validating );
			this.Panel1.Controls.Add( this.supplier_emailTextBox);
			//
			// supplier_mphoneLabel
			//
			this.supplier_mphoneLabel = new System.Windows.Forms.Label();
			this.supplier_mphoneLabel.AutoSize = true;
			this.supplier_mphoneLabel.Location = new System.Drawing.Point( 395, 50 );
			this.supplier_mphoneLabel.Name = "supplier_mphoneLabel";
			this.supplier_mphoneLabel.Size = new System.Drawing.Size( 87, 13 );
			this.supplier_mphoneLabel.TabIndex = 13;
			this.supplier_mphoneLabel.Text = "supplier_mphone";
			this.Panel1.Controls.Add( this.supplier_mphoneLabel );
			//
			// supplier_mphoneTextBox
			//
			this.supplier_mphoneTextBox = new System.Windows.Forms.TextBox();
			this.supplier_mphoneTextBox.Location = new System.Drawing.Point( 492, 50 );
			this.supplier_mphoneTextBox.Name = "supplier_mphoneTextBox";
			this.supplier_mphoneTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.supplier_mphoneTextBox.TabIndex = 14;
			this.supplier_mphoneTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.supplier_mphoneTextBox_Validating );
			this.Panel1.Controls.Add( this.supplier_mphoneTextBox);
			//
			// supplier_wphoneLabel
			//
			this.supplier_wphoneLabel = new System.Windows.Forms.Label();
			this.supplier_wphoneLabel.AutoSize = true;
			this.supplier_wphoneLabel.Location = new System.Drawing.Point( 395, 76 );
			this.supplier_wphoneLabel.Name = "supplier_wphoneLabel";
			this.supplier_wphoneLabel.Size = new System.Drawing.Size( 87, 13 );
			this.supplier_wphoneLabel.TabIndex = 15;
			this.supplier_wphoneLabel.Text = "supplier_wphone";
			this.Panel1.Controls.Add( this.supplier_wphoneLabel );
			//
			// supplier_wphoneTextBox
			//
			this.supplier_wphoneTextBox = new System.Windows.Forms.TextBox();
			this.supplier_wphoneTextBox.Location = new System.Drawing.Point( 492, 76 );
			this.supplier_wphoneTextBox.Name = "supplier_wphoneTextBox";
			this.supplier_wphoneTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.supplier_wphoneTextBox.TabIndex = 16;
			this.supplier_wphoneTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.supplier_wphoneTextBox_Validating );
			this.Panel1.Controls.Add( this.supplier_wphoneTextBox);
			//
			// supplier_faxLabel
			//
			this.supplier_faxLabel = new System.Windows.Forms.Label();
			this.supplier_faxLabel.AutoSize = true;
			this.supplier_faxLabel.Location = new System.Drawing.Point( 419, 102 );
			this.supplier_faxLabel.Name = "supplier_faxLabel";
			this.supplier_faxLabel.Size = new System.Drawing.Size( 63, 13 );
			this.supplier_faxLabel.TabIndex = 17;
			this.supplier_faxLabel.Text = "supplier_fax";
			this.Panel1.Controls.Add( this.supplier_faxLabel );
			//
			// supplier_faxTextBox
			//
			this.supplier_faxTextBox = new System.Windows.Forms.TextBox();
			this.supplier_faxTextBox.Location = new System.Drawing.Point( 492, 102 );
			this.supplier_faxTextBox.Name = "supplier_faxTextBox";
			this.supplier_faxTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.supplier_faxTextBox.TabIndex = 18;
			this.supplier_faxTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.supplier_faxTextBox_Validating );
			this.Panel1.Controls.Add( this.supplier_faxTextBox);
			//
			// supplier_skipeLabel
			//
			this.supplier_skipeLabel = new System.Windows.Forms.Label();
			this.supplier_skipeLabel.AutoSize = true;
			this.supplier_skipeLabel.Location = new System.Drawing.Point( 408, 128 );
			this.supplier_skipeLabel.Name = "supplier_skipeLabel";
			this.supplier_skipeLabel.Size = new System.Drawing.Size( 74, 13 );
			this.supplier_skipeLabel.TabIndex = 19;
			this.supplier_skipeLabel.Text = "supplier_skipe";
			this.Panel1.Controls.Add( this.supplier_skipeLabel );
			//
			// supplier_skipeTextBox
			//
			this.supplier_skipeTextBox = new System.Windows.Forms.TextBox();
			this.supplier_skipeTextBox.Location = new System.Drawing.Point( 492, 128 );
			this.supplier_skipeTextBox.Name = "supplier_skipeTextBox";
			this.supplier_skipeTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.supplier_skipeTextBox.TabIndex = 20;
			this.supplier_skipeTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.supplier_skipeTextBox_Validating );
			this.Panel1.Controls.Add( this.supplier_skipeTextBox);
			//
			// supplier_addressLabel
			//
			this.supplier_addressLabel = new System.Windows.Forms.Label();
			this.supplier_addressLabel.AutoSize = true;
			this.supplier_addressLabel.Location = new System.Drawing.Point( 396, 154 );
			this.supplier_addressLabel.Name = "supplier_addressLabel";
			this.supplier_addressLabel.Size = new System.Drawing.Size( 86, 13 );
			this.supplier_addressLabel.TabIndex = 21;
			this.supplier_addressLabel.Text = "supplier_address";
			this.Panel1.Controls.Add( this.supplier_addressLabel );
			//
			// supplier_addressTextBox
			//
			this.supplier_addressTextBox = new System.Windows.Forms.TextBox();
			this.supplier_addressTextBox.Location = new System.Drawing.Point( 492, 154 );
			this.supplier_addressTextBox.Name = "supplier_addressTextBox";
			this.supplier_addressTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.supplier_addressTextBox.TabIndex = 22;
			this.supplier_addressTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.supplier_addressTextBox_Validating );
			this.Panel1.Controls.Add( this.supplier_addressTextBox);
			//
			// supplier_descriptionLabel
			//
			this.supplier_descriptionLabel = new System.Windows.Forms.Label();
			this.supplier_descriptionLabel.AutoSize = true;
			this.supplier_descriptionLabel.Location = new System.Drawing.Point( 382, 180 );
			this.supplier_descriptionLabel.Name = "supplier_descriptionLabel";
			this.supplier_descriptionLabel.Size = new System.Drawing.Size( 100, 13 );
			this.supplier_descriptionLabel.TabIndex = 23;
			this.supplier_descriptionLabel.Text = "supplier_description";
			this.Panel1.Controls.Add( this.supplier_descriptionLabel );
			//
			// supplier_descriptionTextBox
			//
			this.supplier_descriptionTextBox = new System.Windows.Forms.TextBox();
			this.supplier_descriptionTextBox.Location = new System.Drawing.Point( 492, 180 );
			this.supplier_descriptionTextBox.Name = "supplier_descriptionTextBox";
			this.supplier_descriptionTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.supplier_descriptionTextBox.TabIndex = 24;
			this.supplier_descriptionTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.supplier_descriptionTextBox_Validating );
			this.Panel1.Controls.Add( this.supplier_descriptionTextBox);
			// 
			// panel4
			// 
			this.panel4.Dock = System.Windows.Forms.DockStyle.Right;
			this.panel4.Location = new System.Drawing.Point(656, 0);
			this.panel4.Name = "panel4";
			this.panel4.Size = new System.Drawing.Size(10, 183);
			this.panel4.TabIndex = 3;
			// 
			// panel3
			// 
			this.panel3.Controls.Add(this.Panel1);
			this.panel3.Controls.Add(this.panel4);
			this.panel3.Controls.Add(this.panel5);
			this.panel3.Controls.Add(this.panel6);
			this.panel3.Dock = System.Windows.Forms.DockStyle.Fill;
			this.panel3.Location = new System.Drawing.Point(0, 25);
			this.panel3.Name = "panel3";
			this.panel3.Size = new System.Drawing.Size(666, 183);
			this.panel3.TabIndex = 19;
			// 
			// panel5
			// 
			this.panel5.Dock = System.Windows.Forms.DockStyle.Left;
			this.panel5.Location = new System.Drawing.Point(0, 0);
			this.panel5.Name = "panel5";
			this.panel5.Size = new System.Drawing.Size(10, 183);
			this.panel5.TabIndex = 5;
			// 
			// panel6
			// 
			this.panel6.Dock = System.Windows.Forms.DockStyle.Bottom;
			this.panel6.Location = new System.Drawing.Point(0, 324);
			this.panel6.Name = "panel6";
			this.panel6.Size = new System.Drawing.Size(400, 10);
			this.panel6.TabIndex = 6;
			
			
			// 
			// frmsupplier
			// 
			this.AutoScroll = true;
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(400, 359);
			this.Name = "frmsupplier";
			this.Text = "frmsupplier";
			this.Load += new System.EventHandler(this.frmsupplier_Load);
			this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmsupplier_FormClosing);
			((System.ComponentModel.ISupportInitialize)(this.bindingNavigator1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
			this.bindingNavigator1.ResumeLayout(false);
			this.bindingNavigator1.PerformLayout();
			this.Text = "Supplier";
			((System.ComponentModel.ISupportInitialize)(this.supplierBindingSource)).EndInit();
			this.Controls.Add(this.panel3);
			this.panel3.ResumeLayout(false);
			this.panel3.PerformLayout();
			
			this.Controls.Add(this.bindingNavigator1);
			this.Panel1.ResumeLayout(false);
			this.Panel1.PerformLayout();
			this.ResumeLayout(false);
			this.PerformLayout();
			
		}
		
		#endregion
		
		private System.Windows.Forms.BindingNavigator bindingNavigator1;
		private System.Windows.Forms.ToolStripButton bindingNavigatorAddNewItem;
		private System.Windows.Forms.ToolStripLabel bindingNavigatorCountItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorDeleteItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveFirstItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMovePreviousItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator;
		private System.Windows.Forms.ToolStripTextBox bindingNavigatorPositionItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator1;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveNextItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveLastItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator2;
		private System.Windows.Forms.ToolStripButton toolStripButton1;
		private System.Windows.Forms.ErrorProvider errorProvider1;
		private System.Windows.Forms.Panel Panel1;
		private System.Windows.Forms.BindingSource supplierBindingSource;
		private System.Windows.Forms.TextBox supplier_idTextBox;
		private System.Windows.Forms.Label supplier_idLabel;
		private System.Windows.Forms.TextBox supplier_nameTextBox;
		private System.Windows.Forms.Label supplier_nameLabel;
		private System.Windows.Forms.TextBox supplier_surnameTextBox;
		private System.Windows.Forms.Label supplier_surnameLabel;
		private System.Windows.Forms.TextBox supplier_jobtitleTextBox;
		private System.Windows.Forms.Label supplier_jobtitleLabel;
		private System.Windows.Forms.TextBox supplier_organisationTextBox;
		private System.Windows.Forms.Label supplier_organisationLabel;
		private System.Windows.Forms.TextBox supplier_emailTextBox;
		private System.Windows.Forms.Label supplier_emailLabel;
		private System.Windows.Forms.TextBox supplier_mphoneTextBox;
		private System.Windows.Forms.Label supplier_mphoneLabel;
		private System.Windows.Forms.TextBox supplier_wphoneTextBox;
		private System.Windows.Forms.Label supplier_wphoneLabel;
		private System.Windows.Forms.TextBox supplier_faxTextBox;
		private System.Windows.Forms.Label supplier_faxLabel;
		private System.Windows.Forms.TextBox supplier_skipeTextBox;
		private System.Windows.Forms.Label supplier_skipeLabel;
		private System.Windows.Forms.TextBox supplier_addressTextBox;
		private System.Windows.Forms.Label supplier_addressLabel;
		private System.Windows.Forms.TextBox supplier_descriptionTextBox;
		private System.Windows.Forms.Label supplier_descriptionLabel;
		private System.Windows.Forms.Panel panel3;
		private System.Windows.Forms.Panel panel4;
		private System.Windows.Forms.Panel panel5;
		private System.Windows.Forms.Panel panel6;
		
	}
}

