/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using MySql.Data.MySqlClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity;
using MySqlDB;
using System.Reflection;

namespace ArtFlex
{
    public partial class frmwaybills : Form
    {
        private ArtflexDbContext context;
        private int supplier;

        public frmwaybills()
        {
            InitializeComponent();
        }

        private void frmwaybills_Load(object sender, EventArgs e)
        {
            supplier = -1;
            context = new ArtflexDbContext();

            //context.waybills.Where(s => s.supplier_id == -1).Include(s => s.suppliers).Load();
            context.waybills.Where(s => s.supplier_id == supplier).Load();
            BindingList<waybills> _entities = context.waybills.Local.ToBindingList();
            waybillsBindingSource.CurrentChanged += waybillsBindingSource_CurrentChanged;
            waybillsBindingSource.DataSource = _entities;

            System.Windows.Forms.DataGridViewTextBoxColumn col_waybill_id = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_waybill_id.DataPropertyName = "waybill_id";
            col_waybill_id.HeaderText = "ID";
            col_waybill_id.Name = "col_waybill_id";
            dataGridViewWaybills.Columns.Add(col_waybill_id);

            System.Windows.Forms.DataGridViewTextBoxColumn col_waybill_name = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_waybill_name.DataPropertyName = "waybill_name";
            col_waybill_name.HeaderText = "Накладная";
            col_waybill_name.Name = "col_waybill_name";
            dataGridViewWaybills.Columns.Add(col_waybill_name);

            //System.Windows.Forms.DataGridViewTextBoxColumn col_supplier_name = new System.Windows.Forms.DataGridViewTextBoxColumn();
            //col_supplier_name.DataPropertyName = "SupplierName";
            //col_supplier_name.HeaderText = "Поставщик";
            //col_supplier_name.Name = "col_supplier_name";
            //dataGridViewWaybills.Columns.Add(col_supplier_name);

            System.Windows.Forms.DataGridViewComboBoxColumn col_supplier_name = new System.Windows.Forms.DataGridViewComboBoxColumn();
            col_supplier_name.DataSource = context.suppliers.ToList();
            col_supplier_name.DataPropertyName = "supplier_id";
            col_supplier_name.DisplayMember = "supplier_name";
            col_supplier_name.ValueMember = "supplier_id";
            col_supplier_name.HeaderText = "Поставщик";
            col_supplier_name.Name = "col_supplier_id";
            col_supplier_name.ToolTipText = "Pick the column from the foreign table to use as friendly value for this lookup.";
            col_supplier_name.DisplayStyle = DataGridViewComboBoxDisplayStyle.Nothing;
            dataGridViewWaybills.Columns.Add(col_supplier_name);

            System.Windows.Forms.DataGridViewTextBoxColumn col_waybill_date = new System.Windows.Forms.DataGridViewTextBoxColumn();
            col_waybill_date.DataPropertyName = "waybill_date";
            col_waybill_date.HeaderText = "Дата поставки";
            col_waybill_date.Name = "col_waybill_date";
            dataGridViewWaybills.Columns.Add(col_waybill_date);

            this.dataGridViewWaybills.AutoGenerateColumns = false;
            this.dataGridViewWaybills.DataSource = this.waybillsBindingSource;


            // dataGridViewSupplies
            System.Windows.Forms.DataGridViewTextBoxColumn colsupply_id = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colsupply_id.DataPropertyName = "supply_id";
            colsupply_id.HeaderText = "supply_id";
            colsupply_id.Name = "colsupply_id";
            dataGridViewSupplies.Columns.Add(colsupply_id);

            System.Windows.Forms.DataGridViewTextBoxColumn colsupply_quantity = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colsupply_quantity.DataPropertyName = "supply_quantity";
            colsupply_quantity.HeaderText = "supply_quantity";
            colsupply_quantity.Name = "colsupply_quantity";
            dataGridViewSupplies.Columns.Add(colsupply_quantity);

            System.Windows.Forms.DataGridViewComboBoxColumn colmaterial_id = new System.Windows.Forms.DataGridViewComboBoxColumn();
            colmaterial_id.DataSource = context.materials.ToList();
            colmaterial_id.DataPropertyName = "material_id";
            colmaterial_id.DisplayMember = "material_name";
            colmaterial_id.ValueMember = "material_id";
            colmaterial_id.HeaderText = "material_id";
            colmaterial_id.Name = "colmaterial_id";
            colmaterial_id.ToolTipText = "Pick the column from the foreign table to use as friendly value for this lookup.";
            colmaterial_id.DisplayStyle = DataGridViewComboBoxDisplayStyle.Nothing;
            dataGridViewSupplies.Columns.Add(colmaterial_id);

            System.Windows.Forms.DataGridViewTextBoxColumn colsupply_summ = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colsupply_summ.DataPropertyName = "supply_summ";
            colsupply_summ.HeaderText = "supply_summ";
            colsupply_summ.Name = "colsupply_summ";
            dataGridViewSupplies.Columns.Add(colsupply_summ);

            System.Windows.Forms.DataGridViewTextBoxColumn colsupply_costunit = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colsupply_costunit.DataPropertyName = "supply_costunit";
            colsupply_costunit.HeaderText = "supply_costunit";
            colsupply_costunit.Name = "colsupply_costunit";
            dataGridViewSupplies.Columns.Add(colsupply_costunit);

            System.Windows.Forms.DataGridViewTextBoxColumn colsupply_description = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colsupply_description.DataPropertyName = "supply_description";
            colsupply_description.HeaderText = "supply_description";
            colsupply_description.Name = "colsupply_description";
            dataGridViewSupplies.Columns.Add(colsupply_description);

            System.Windows.Forms.DataGridViewComboBoxColumn colwaybill_id = new System.Windows.Forms.DataGridViewComboBoxColumn();
            colwaybill_id.DataSource = context.waybills.ToList();
            colwaybill_id.DataPropertyName = "waybill_id";
            colwaybill_id.DisplayMember = "waybill_name";
            colwaybill_id.ValueMember = "waybill_id";
            colwaybill_id.HeaderText = "waybill_id";
            colwaybill_id.Name = "colwaybill_id";
            colwaybill_id.ToolTipText = "Pick the column from the foreign table to use as friendly value for this lookup.";
            colwaybill_id.DisplayStyle = DataGridViewComboBoxDisplayStyle.Nothing;
            dataGridViewSupplies.Columns.Add(colwaybill_id);

            System.Windows.Forms.DataGridViewTextBoxColumn colsupply_createtime = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colsupply_createtime.DataPropertyName = "supply_createtime";
            colsupply_createtime.HeaderText = "supply_createtime";
            colsupply_createtime.Name = "colsupply_createtime";
            colsupply_createtime.ReadOnly = true;
            colsupply_createtime.DefaultCellStyle.BackColor = Color.LightGray;
            dataGridViewSupplies.Columns.Add(colsupply_createtime);


            suppliesBindingSource.DataSource = waybillsBindingSource;
            suppliesBindingSource.DataMember = "supplies";
            dataGridViewSupplies.AutoGenerateColumns = false;


            dataGridViewSupplies.DataSource = suppliesBindingSource;

            // Supplier selector
            this.supplierComboBox.DataSource = context.suppliers.ToList();
            this.supplierComboBox.DisplayMember = "supplier_name";
            this.supplierComboBox.ValueMember = "supplier_id";
        }

        private void Save_Click(object sender, EventArgs e)
        {
            if (!this.Validate()) return;
            waybillsBindingSource.EndEdit();
            suppliesBindingSource.EndEdit();
            context.SaveChanges();
        }

        private void frmwaybills_FormClosing(object sender, FormClosingEventArgs e)
        {
            e.Cancel = false;
        }

        private void dataGridView1_CellValidating(object sender, DataGridViewCellValidatingEventArgs e)
        {
            string s;
            DataGridViewRow row = dataGridViewSupplies.Rows[e.RowIndex];
            object value = e.FormattedValue;
            e.Cancel = false;
            row.ErrorText = "";
            if (row.IsNewRow) return;
            if (e.ColumnIndex == 0)
            {
                int v;
                if ((value is DBNull) || string.IsNullOrEmpty(value.ToString()))
                {
                    e.Cancel = true;
                    row.ErrorText = "The field supply_id is required";
                    return;
                }
                s = value.ToString();
                if (!int.TryParse(s, out v))
                {
                    e.Cancel = true;
                    row.ErrorText = "The field supply_id must be int.";
                    return;
                }
            }
            if (e.ColumnIndex == 1)
            {
                double v;
                if ((value is DBNull) || string.IsNullOrEmpty(value.ToString()))
                {
                    e.Cancel = true;
                    row.ErrorText = "The field supply_quantity is required";
                    return;
                }
                s = value.ToString();
                if (!double.TryParse(s, out v))
                {
                    e.Cancel = true;
                    row.ErrorText = "The field supply_quantity must be double.";
                    return;
                }
            }
            if (e.ColumnIndex == 3)
            {
                double v;
                if ((value is DBNull) || string.IsNullOrEmpty(value.ToString()))
                {
                    e.Cancel = true;
                    row.ErrorText = "The field supply_summ is required";
                    return;
                }
                s = value.ToString();
                if (!double.TryParse(s, out v))
                {
                    e.Cancel = true;
                    row.ErrorText = "The field supply_summ must be double.";
                    return;
                }
            }
            if (e.ColumnIndex == 4)
            {
                double v;
                if ((value is DBNull) || string.IsNullOrEmpty(value.ToString()))
                {
                    e.Cancel = true;
                    row.ErrorText = "The field supply_costunit is required";
                    return;
                }
                s = value.ToString();
                if (!double.TryParse(s, out v))
                {
                    e.Cancel = true;
                    row.ErrorText = "The field supply_costunit must be double.";
                    return;
                }
            }
            if (e.ColumnIndex == 5)
            {
                if ((value is DBNull) || string.IsNullOrEmpty(value.ToString()))
                {
                    e.Cancel = true;
                    row.ErrorText = "The field supply_description is required";
                    return;
                }
            }
            if (e.ColumnIndex == 7)
            {
                if ((value is DBNull) || string.IsNullOrEmpty(value.ToString()))
                {
                    e.Cancel = true;
                    row.ErrorText = "The field supply_createtime is required";
                    return;
                }
            }
        }

        private void dataGridView1_DataError(object sender, DataGridViewDataErrorEventArgs e)
        {
            dataGridViewSupplies.Rows[e.RowIndex].ErrorText = e.Exception.Message;
            e.Cancel = true;
        }
        private void waybillsBindingSource_CurrentChanged(object sender, EventArgs e)
        {
            suppliesBindingSource.DataSource = ((waybills)waybillsBindingSource.Current);
            suppliesBindingSource.DataMember = "supplies";
            dataGridViewSupplies.Refresh();
        }
        private void bindingNavigatorAddNewItem_Click(object sender, EventArgs e)
        {
            waybillsBindingSource.AddNew();
        }


    }
}
