//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtFlex
{
    using System;
    using System.Collections.Generic;
    
    public partial class materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public materials()
        {
            this.consumption = new HashSet<consumption>();
            this.rests = new HashSet<rests>();
            this.supply = new HashSet<supply>();
        }
    
        public long material_id { get; set; }
        public long category_id { get; set; }
        public string material_name { get; set; }
        public string material_size { get; set; }
        public Nullable<long> material_rollwidth { get; set; }
        public long unit_id { get; set; }
        public string material_description { get; set; }
        public System.DateTime material_createtime { get; set; }
    
        public virtual categories categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consumption> consumption { get; set; }
        public virtual units units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rests> rests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supply> supply { get; set; }
    }
}
