//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtFlex
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelArtFlexEntities : DbContext
    {
        public ModelArtFlexEntities()
            : base("name=ModelArtFlexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<consumption> consumption { get; set; }
        public virtual DbSet<employees> employees { get; set; }
        public virtual DbSet<job_titles> job_titles { get; set; }
        public virtual DbSet<materials> materials { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<rests> rests { get; set; }
        public virtual DbSet<supplier> supplier { get; set; }
        public virtual DbSet<supply> supply { get; set; }
        public virtual DbSet<units> units { get; set; }
        public virtual DbSet<waybills> waybills { get; set; }
    }
}
